import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { site, faq, mergedPages, retiredPages } from "./site.mjs";
import { productGuides } from "./guides-product.mjs";
import { launcherGuides } from "./guides-launchers.mjs";
import { gameGuides } from "./guides-games.mjs";

export const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
export const guides = [...productGuides, ...launcherGuides, ...gameGuides];
const esc = (value) =>
  String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
const date = (value) =>
  new Date(`${value}T12:00:00Z`).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  });
const url = (path) => `${site.origin}${path}`;
const assetVersion = (name) =>
  createHash("sha256")
    .update(
      readFileSync(resolve(root, `scripts/landing/${name}`), "utf8").replaceAll(
        "\r\n",
        "\n",
      ),
    )
    .digest("hex")
    .slice(0, 12);
const shotUrl = (key) => `/images/${site.screenshots[key].file}`;
const arrow = '<span aria-hidden="true">↗</span>';
const download = (label = "Download for Windows", secondary = false) =>
  `<a class="button${secondary ? " secondary" : ""}" href="${site.download}">${label} <span aria-hidden="true">↓</span></a>`;

function navigation() {
  const links =
    '<a href="/#features">Features</a><a href="/#imports">Imports</a><a href="/#emulators">Emulators</a><a href="/guides/">Guides</a>';
  return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="nav-wrap"><a class="brand" href="/" aria-label="PlayCounter home"><img src="/icon.png" width="34" height="34" alt="" />PlayCounter</a><nav class="desktop-nav" aria-label="Main">${links}</nav><a class="nav-download" href="${site.download}">Download <span aria-hidden="true">↓</span></a><details class="mobile-menu"><summary>Menu</summary><nav aria-label="Mobile">${links}<a href="${site.download}">Download for Windows</a></nav></details></div></header>`;
}

function footer() {
  return `<footer class="site-footer"><div class="footer-top"><a class="brand" href="/"><img src="/icon.png" width="30" height="30" alt="" />PlayCounter</a><p>Automatic playtime tracking for Windows.</p><nav aria-label="Footer"><a href="/guides/">Guides</a><a href="${site.repository}">Source code ${arrow}</a><a href="${site.discord}">Discord ${arrow}</a><a href="${site.releases}">Releases ${arrow}</a></nav></div><div class="footer-bottom"><span>© 2026 PlayCounter</span><div><a href="/is-playcounter-safe/">Downloads &amp; privacy</a><a href="/datenschutz">Privacy policy</a><a href="/impressum">Legal notice</a></div></div><p class="trademarks">Third-party game artwork and trademarks belong to their respective owners.</p></footer>`;
}

function screenshot(key, { eager = false, caption = true } = {}) {
  const shot = site.screenshots[key];
  return `<figure class="screenshot"><a href="${shotUrl(key)}" target="_blank" rel="noopener" aria-label="Open full-size screenshot: ${esc(shot.alt)}"><img src="${shotUrl(key)}" width="${shot.width}" height="${shot.height}" alt="${esc(shot.alt)}" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async" /></a>${caption ? `<figcaption>PlayCounter ${site.version} · Example data · Open image to see details</figcaption>` : ""}</figure>`;
}

function shell({
  title,
  description,
  path,
  body,
  graph = [],
  lang = "en",
  noindex = false,
}) {
  const social = site.screenshots.social;
  const website = {
    "@type": "WebSite",
    "@id": url("/#website"),
    url: url("/"),
    name: site.name,
    inLanguage: "en",
    description: site.description,
  };
  const organization = {
    "@type": "Organization",
    "@id": url("/#organization"),
    name: site.name,
    url: url("/"),
    logo: url("/icon.png"),
    sameAs: [site.repository],
  };
  return `<!doctype html>
<!-- Generated by scripts/landing/build.mjs. Edit content in scripts/landing/. -->
<html lang="${lang}">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}" />
<meta name="robots" content="${noindex ? "noindex, follow" : "index, follow, max-image-preview:large"}" />
<meta name="theme-color" content="#2457e6" />
<meta name="application-name" content="PlayCounter" />
${noindex ? "" : `<link rel="canonical" href="${url(path)}" />`}
<link rel="icon" href="/icon.png" />
<link rel="apple-touch-icon" href="/icon.png" />
<link rel="stylesheet" href="/styles.css?v=${assetVersion("styles.css")}" />
<script src="/site.js?v=${assetVersion("site.js")}" defer></script>
<link rel="sitemap" type="application/xml" href="/sitemap.xml" />
<meta property="og:title" content="${esc(title)}" />
<meta property="og:description" content="${esc(description)}" />
<meta property="og:type" content="${graph.some((item) => item["@type"] === "Article") ? "article" : "website"}" />
<meta property="og:url" content="${url(path)}" />
<meta property="og:site_name" content="PlayCounter" />
<meta property="og:locale" content="${lang === "de" ? "de_DE" : "en_US"}" />
<meta property="og:image" content="${url(shotUrl("social"))}" />
<meta property="og:image:width" content="${social.width}" />
<meta property="og:image:height" content="${social.height}" />
<meta property="og:image:alt" content="${esc(social.alt)}" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${esc(title)}" />
<meta name="twitter:description" content="${esc(description)}" />
<meta name="twitter:image" content="${url(shotUrl("social"))}" />
<meta name="twitter:image:alt" content="${esc(social.alt)}" />
${noindex ? "" : `<script type="application/ld+json">${JSON.stringify({ "@context": "https://schema.org", "@graph": [website, organization, ...graph] }, null, 2).replaceAll("<", "\\u003c")}</script>`}
</head>
<body>${navigation()}${body}${footer()}</body>
</html>
`;
}

function guideCard(guide) {
  return `<a class="guide-card" href="/${guide.slug}/"><span class="eyebrow">${guide.category}</span><h3>${esc(guide.title)}</h3><span class="card-link">Read guide <span aria-hidden="true">→</span></span></a>`;
}

function home() {
  const features = [
    [
      "Automatic sessions",
      "Open a game as usual. PlayCounter starts tracking recognized games and saves the session when they close.",
    ],
    [
      "One game library",
      "See your games with covers, totals and provider tabs. Search and sort to find what you want.",
    ],
    [
      "History & statistics",
      "Browse recorded sessions and your playtime statistics. Add a session or adjust a total when needed.",
    ],
    [
      "A library that feels like yours",
      "Choose grid or list layouts, adjust card sizes and customize covers. Switch between light and dark themes.",
    ],
    [
      "Useful while you play",
      "Keep the app in the tray, use optional overlays and shortcuts, or enable game launching from your library.",
    ],
    [
      "Control over your tracking",
      "Review uncertain matches, add local games and exclude processes. Back up your library from Settings.",
    ],
  ];
  const importerCards = site.importers
    .map(
      (item) =>
        `<article class="support-card"><div class="support-heading"><span class="provider-logo ${item.id}"><img src="${item.logo}" width="38" height="38" alt="" loading="lazy" /></span><div><h3>${esc(item.name)}</h3><span>${item.method}</span></div></div><p>${item.detail}</p><a class="text-link" href="${item.guide}">How to import ${item.id === "steam" ? "Steam" : "Xbox"} playtime <span aria-hidden="true">→</span></a></article>`,
    )
    .join("");
  const emulatorCards = site.emulators
    .map(
      (item) =>
        `<article class="support-card"><div class="support-heading"><span class="provider-logo ${item.id}"><img src="${item.logo}" width="42" height="42" alt="" loading="lazy" /></span><div><h3>${item.name}</h3><span>${item.systems}</span></div></div><p>${item.detail}</p></article>`,
    )
    .join("");
  const selected = [
    "check-playtime-minecraft",
    "check-playtime-on-steam",
    "check-playtime-xbox-game-pass",
    "check-playtime-fortnite",
    "check-playtime-roblox",
    "total-playtime-across-all-launchers",
  ];
  const body = `<main id="main">
<section class="hero wrap"><p class="eyebrow">Automatic playtime tracking for Windows</p><h1>Your games.<br /><span>Your playtime.</span></h1><p class="hero-lede">Track your games automatically, wherever you launch them.<br class="desktop-break" /> Bring available Steam and Xbox hours into one game library.</p><div class="hero-actions">${download()}<a class="button secondary" href="#features">Explore the app <span aria-hidden="true">↓</span></a></div><p class="download-meta">Free · No PlayCounter account · Windows</p><p class="milestone"><span aria-hidden="true" class="status-dot"></span>${site.milestone}</p>${screenshot("library", { eager: true })}</section>
<section id="features" class="section wrap"><div class="section-heading"><p class="eyebrow">The app</p><h2>Launch. Play. It’s recorded.</h2><p>A live timer while you play. A library and session history to come back to.</p></div><div class="feature-grid">${features.map(([title, detail], index) => `<article class="feature"><span class="feature-mark" aria-hidden="true">${["◷", "▦", "↗", "◐", "⌘", "✓"][index]}</span><h3>${title}</h3><p>${detail}</p></article>`).join("")}</div><div class="screenshots-grid">${screenshot("now")}${screenshot("history")}</div><p class="section-note">Your recorded sessions and history stay on your PC. Online features include game matching and installation presence. <a href="/datenschutz#en">What the app sends online</a>.</p></section>
<section id="imports" class="section section-tint"><div class="wrap"><div class="section-heading"><p class="eyebrow">Launcher imports</p><h2>Bring your earlier hours along.</h2><p>Automatic tracking works regardless of launcher. Imports add available previous playtime for a more complete library.</p></div><div class="support-grid">${importerCards}</div><div class="import-explainer"><div><h3>Track from any launcher</h3><p>Recognized games from Epic, GOG, EA, Ubisoft, Battle.net, itch.io and standalone installations track as you play. No importer or special launch setup is needed.</p></div><div><h3>Clear totals, no added overlap</h3><p>Imported hours are totals, not past sessions. PlayCounter uses the higher local or imported total for a matched game. <a href="/total-playtime-across-all-launchers/#totals">See how totals work</a>.</p></div></div></div></section>
<section id="emulators" class="section wrap"><div class="section-heading"><p class="eyebrow">Emulated games</p><h2>The game inside the emulator.</h2><p>Dedicated detection for DOSBox and Dolphin gives recognized games their own place in your library.</p></div><div class="support-grid">${emulatorCards}</div><p class="section-note">Some matches need your review. <a href="/playtime-tracker-for-emulators/">See supported variants, setup and detection details <span aria-hidden="true">→</span></a></p></section>
<section id="start" class="section section-tint"><div class="wrap"><div class="section-heading"><p class="eyebrow">Get started</p><h2>Ready for your next session.</h2></div><ol class="steps"><li><span>01</span><h3>Install PlayCounter</h3><p>Download the free Windows app and open it. No PlayCounter account to create.</p></li><li><span>02</span><h3>Launch your game</h3><p>Keep PlayCounter running, including in the tray. Start your game the usual way.</p></li><li><span>03</span><h3>See your playtime</h3><p>Check Now Playing, then find your game and recorded sessions in the library and history.</p></li></ol><p class="section-note">If a game needs a match, review it in Discovered. <a href="/how-automatic-game-detection-works/">How detection works</a>.</p></div></section>
<section id="guides" class="section wrap"><div class="section-heading heading-row"><div><p class="eyebrow">Useful guides</p><h2>Find the hours you’re looking for.</h2></div><a class="text-link" href="/guides/">All guides <span aria-hidden="true">→</span></a></div><div class="guide-grid">${selected.map((slug) => guideCard(guides.find((guide) => guide.slug === slug))).join("")}</div></section>
<section id="faq" class="section wrap faq-section"><div class="section-heading"><p class="eyebrow">Questions</p><h2>A few things to know.</h2></div><div class="faq-list">${faq.map(([question, answer]) => `<details><summary>${question}</summary><div><p>${answer}</p></div></details>`).join("")}</div></section>
<section id="download" class="download-section wrap"><div><p class="eyebrow">PlayCounter for Windows</p><h2>Your next session starts here.</h2><p>Free to use. Desktop source available on GitHub.</p></div><div class="download-block">${download()}<p><a href="${site.releases}">Release ${site.version} · ${(site.installerBytes / 1000000).toFixed(1)} MB installer</a></p><a class="small-link" href="/is-playcounter-safe/">Download and verification details</a></div></section>
</main>`;
  const software = {
    "@type": "SoftwareApplication",
    "@id": url("/#software"),
    name: site.name,
    url: url("/"),
    description: site.description,
    applicationCategory: "UtilitiesApplication",
    operatingSystem: "Windows",
    softwareVersion: site.version,
    dateModified: site.releaseDate,
    downloadUrl: site.download,
    releaseNotes: site.releases,
    screenshot: url(shotUrl("library")),
    image: url(shotUrl("social")),
    author: { "@id": url("/#organization") },
    license: "https://opensource.org/license/mit",
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
      url: url("/#download"),
    },
    featureList: [
      "Automatic game playtime tracking across launchers",
      "Local session history and game library",
      "Steam and Xbox playtime imports",
      "DOSBox and Dolphin per-game detection",
      "Customizable library views and covers",
    ],
  };
  return shell({
    title: "Free Automatic Game Playtime Tracker for Windows | PlayCounter",
    description: site.description,
    path: "/",
    body,
    graph: [software],
  });
}

function breadcrumbs(items) {
  return {
    "@type": "BreadcrumbList",
    itemListElement: items.map(([name, path], index) => ({
      "@type": "ListItem",
      position: index + 1,
      name,
      item: url(path),
    })),
  };
}

function guidePage(guide) {
  const path = `/${guide.slug}/`;
  const body = `<main id="main" class="article-wrap"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><a href="/guides/">Guides</a><span aria-hidden="true">/</span><span>${guide.category}</span></nav><article><header class="article-header"><p class="eyebrow">${guide.category}</p><h1>${esc(guide.title)}</h1><p class="article-answer">${guide.answer}</p><p class="article-meta">By the <a href="${site.repository}">PlayCounter project</a> · Updated <time datetime="${site.reviewed}">${date(site.reviewed)}</time></p></header><nav class="contents" aria-label="On this page"><strong>On this page</strong><ul>${guide.sections.map((section) => `<li><a href="#${section.id}">${section.title}</a></li>`).join("")}</ul></nav><div class="article-body">${guide.sections.map((section) => `<section id="${section.id}"><h2>${section.title}</h2>${section.html}${section.screenshot ? screenshot(section.screenshot) : ""}</section>`).join("")}<section class="sources" id="sources"><h2>Sources &amp; further details</h2><ul>${guide.sources.map((source) => `<li><a href="${esc(source.url)}">${esc(source.label)}</a></li>`).join("")}</ul></section></div></article><aside class="article-download" aria-label="Get PlayCounter"><div><h2>Track your next PC session.</h2><p>Automatic tracking, local history and one game library.</p></div>${download()}</aside><section class="related"><h2>Related guides</h2><div class="guide-grid">${guide.related.map((slug) => guideCard(guides.find((item) => item.slug === slug))).join("")}</div><a class="text-link" href="/guides/">All PlayCounter guides <span aria-hidden="true">→</span></a></section></main>`;
  const article = {
    "@type": "Article",
    "@id": url(`${path}#article`),
    headline: guide.title,
    description: guide.description,
    dateModified: site.reviewed,
    inLanguage: "en",
    author: { "@id": url("/#organization") },
    publisher: { "@id": url("/#organization") },
    mainEntityOfPage: url(path),
    image: url(
      shotUrl(
        guide.sections.find((section) => section.screenshot)?.screenshot ??
          "library",
      ),
    ),
  };
  return shell({
    title: `${guide.title} | PlayCounter`,
    description: guide.description,
    path,
    body,
    graph: [
      article,
      breadcrumbs([
        ["Home", "/"],
        ["Guides", "/guides/"],
        [guide.title, path],
      ]),
    ],
  });
}

function guideIndex() {
  const categories = ["Using PlayCounter", "Launcher guides", "Game guides"];
  const body = `<main id="main" class="wrap guide-index"><header class="section-heading"><p class="eyebrow">PlayCounter guides</p><h1>Find your playtime.<br />Get your setup right.</h1><p>Direct instructions for checking game hours, importing available totals and recording new sessions on Windows.</p></header><nav class="guide-categories" aria-label="Guide categories">${categories.map((category, index) => `<a href="#category-${index}">${category}</a>`).join("")}</nav>${categories
    .map(
      (category, index) =>
        `<section id="category-${index}" class="guide-category"><h2>${category}</h2><div class="guide-grid">${guides
          .filter((guide) => guide.category === category)
          .map(guideCard)
          .join("")}</div></section>`,
    )
    .join("")}</main>`;
  return shell({
    title: "Playtime Guides: Games, Launchers & Imports | PlayCounter",
    description:
      "Practical guides to checking game hours, importing Steam and Xbox playtime, tracking Minecraft and other PC games, and setting up emulators.",
    path: "/guides/",
    body,
    graph: [
      breadcrumbs([
        ["Home", "/"],
        ["Guides", "/guides/"],
      ]),
    ],
  });
}

function legalPage(name) {
  const content = readFileSync(
    resolve(root, `scripts/landing/legal/${name}.html`),
    "utf8",
  ).trim();
  const privacy = name === "datenschutz";
  return shell({
    title: privacy
      ? "Datenschutzerklärung / Privacy Policy | PlayCounter"
      : "Impressum / Legal Notice | PlayCounter",
    description: privacy
      ? "Privacy policy for the PlayCounter website and desktop app: local history, game matching, imports, emulator detection and installation presence."
      : "Legal notice, operator and contact information for PlayCounter.",
    path: `/${name}`,
    lang: "de",
    body: `<main id="main" class="article-wrap legal article-body">${content}</main>`,
  });
}

function notFound() {
  return shell({
    title: "Page not found | PlayCounter",
    description:
      "This page is no longer available. Browse the current PlayCounter features and practical playtime guides.",
    path: "/404",
    noindex: true,
    body: `<main id="main" class="wrap not-found"><p class="eyebrow">404 · Page not found</p><h1>This page isn’t here.</h1><p>Find current app features on the homepage, or browse the playtime guides.</p><div class="hero-actions"><a class="button" href="/">PlayCounter home</a><a class="button secondary" href="/guides/">Browse guides</a></div></main>`,
  });
}

export function buildOutputs() {
  const outputs = new Map([
    ["index.html", home()],
    ["guides/index.html", guideIndex()],
    ["datenschutz.html", legalPage("datenschutz")],
    ["impressum.html", legalPage("impressum")],
    ["404.html", notFound()],
  ]);
  for (const guide of guides)
    outputs.set(`${guide.slug}/index.html`, guidePage(guide));
  const pages = [
    "/",
    "/guides/",
    ...guides.map((guide) => `/${guide.slug}/`),
    "/datenschutz",
    "/impressum",
  ];
  outputs.set(
    "sitemap.xml",
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.map((path) => `  <url><loc>${url(path)}</loc><lastmod>${site.reviewed}</lastmod></url>`).join("\n")}\n</urlset>\n`,
  );
  outputs.set(
    "llms.txt",
    `# PlayCounter\n\n> ${site.description}\n\n- Public Windows release: ${site.version}, published ${site.releaseDate}.\n- Free desktop app; no PlayCounter account required. Desktop source is MIT-licensed. The current production API is private.\n- Automatic tracking follows recognized running games, regardless of launcher. Unknown or ambiguous games can be reviewed locally.\n- Historical importers: Steam (local account files) and Xbox (optional Microsoft sign-in; playtime availability varies by game).\n- Imported totals do not recreate sessions. For a matched game, the displayed total is the higher local total or largest imported provider total, not their sum.\n- Dedicated per-game emulator detection: DOSBox and Dolphin. Recognition depends on exposed game identifiers or titles.\n- Recorded sessions and history stay on the PC. Matching, metadata, updates and pseudonymous installation presence use online services; optional imports have additional data flows.\n\n## Official pages\n\n- [Features, imports and download](${url("/")})\n- [Guides](${url("/guides/")})\n- [Playtime totals](${url("/total-playtime-across-all-launchers/")})\n- [Emulator support](${url("/playtime-tracker-for-emulators/")})\n- [Privacy policy](${url("/datenschutz#en")})\n- [Download verification and source](${url("/is-playcounter-safe/")})\n- [Public desktop source](${site.repository})\n- [Current releases](${site.releases})\n`,
  );
  // Azure treats /path and /path/ as duplicate routes. Emit one rule and let
  // trailingSlash: "auto" normalize file and directory URLs.
  const redirects = Object.entries(mergedPages).flatMap(([slug, destination]) =>
    ["", "/index", "/index.html", ".html"].map((suffix) => ({
      route: `/${slug}${suffix}`,
      redirect: destination,
      statusCode: 301,
    })),
  );
  // SWA's /index.html rules also match the directory itself. Redirect the
  // extensionless alias instead, after SWA's built-in HTML normalization.
  const aliases = [
    "index",
    ...["guides", ...guides.map((guide) => guide.slug)].map(
      (slug) => `${slug}/index`,
    ),
  ];
  const config = {
    trailingSlash: "auto",
    routes: [
      ...["datenschutz", "impressum"].flatMap((name) => [
        { route: `/${name}`, rewrite: `/${name}.html` },
        { route: `/${name}.html`, redirect: `/${name}`, statusCode: 301 },
      ]),
      ...redirects,
      ...aliases.map((alias) => ({
        route: `/${alias}`,
        redirect: alias === "index" ? "/" : `/${alias.slice(0, -6)}/`,
        statusCode: 301,
      })),
      {
        route: "/images/*",
        headers: { "Cache-Control": "public, max-age=31536000, immutable" },
      },
      {
        route: "/brands/*",
        headers: { "Cache-Control": "public, max-age=604800" },
      },
      {
        route: "/styles.css",
        headers: { "Cache-Control": "public, max-age=3600, must-revalidate" },
      },
      {
        route: "/site.js",
        headers: { "Cache-Control": "public, max-age=3600, must-revalidate" },
      },
    ],
    responseOverrides: { 404: { rewrite: "/404.html", statusCode: 404 } },
    globalHeaders: {
      "Cache-Control": "public, max-age=0, must-revalidate",
      "X-Content-Type-Options": "nosniff",
      "Referrer-Policy": "strict-origin-when-cross-origin",
      "Permissions-Policy": "camera=(), geolocation=(), microphone=()",
      "X-Frame-Options": "DENY",
    },
  };
  outputs.set(
    "staticwebapp.config.json",
    `${JSON.stringify(config, null, 2)}\n`,
  );
  outputs.set(
    "robots.txt",
    `User-agent: *\nAllow: /\n\nSitemap: ${url("/sitemap.xml")}\n`,
  );
  outputs.set(
    "styles.css",
    readFileSync(resolve(root, "scripts/landing/styles.css"), "utf8"),
  );
  outputs.set(
    "site.js",
    readFileSync(resolve(root, "scripts/landing/site.js"), "utf8"),
  );
  return outputs;
}

export const removedHtml = [...Object.keys(mergedPages), ...retiredPages].map(
  (slug) => `${slug}/index.html`,
);

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const outputs = buildOutputs();
  if (process.argv.includes("--check")) {
    const stale = [...outputs].filter(([path, content]) => {
      try {
        return (
          readFileSync(resolve(root, "landing", path), "utf8").replaceAll(
            "\r\n",
            "\n",
          ) !== content.replaceAll("\r\n", "\n")
        );
      } catch {
        return true;
      }
    });
    if (stale.length)
      throw new Error(
        `Generated landing files are out of date. Run node scripts/landing/build.mjs.\n${stale.map(([path]) => path).join("\n")}`,
      );
    console.log(`Generated output is current (${outputs.size} files).`);
  } else {
    for (const [path, content] of outputs) {
      const destination = resolve(root, "landing", path);
      mkdirSync(dirname(destination), { recursive: true });
      writeFileSync(destination, content);
    }
    console.log(`Built ${outputs.size} static files in landing/.`);
  }
}
