import type { ViewId } from "../../store";
import { TOUR_DEMO_GAME } from "./tourDemoGame";

export type TourAdvance =
  | { type: "anchor-present"; selector: string }
  | {
      type: "event";
      name:
        | "mygames.demo-session-logged"
        | "mygames.demo-launch-attempted"
        | "library.demo-shelf-created";
    };

export type TourEventName = Extract<TourAdvance, { type: "event" }>["name"];

export const TOUR_CATEGORIES = [
  { id: "getting-started", title: "Getting started" },
  { id: "library", title: "Your library" },
  { id: "playtime", title: "Playtime & stats" },
  { id: "detection", title: "Detection & launching" },
  { id: "settings", title: "Settings & support" },
] as const;

export type TourStep = {
  id: string;
  title: string;
  body: string;
  view: ViewId | "keep" | "return";
  anchor?: string;
  /** Prefer these targets, in order, as an action opens a menu or dialog. */
  anchorTargets?: string[];
  additionalAnchors?: string[];
  /** Place instructions outside this container while highlighting its detail. */
  positionAnchor?: string;
  cardPlacement?: "below";
  optional?: boolean;
  interactive?: boolean;
  manualAdvance?: boolean;
  persistentInteraction?: boolean;
  scrollIntoView?: boolean;
  allow?: string[];
  advanceOn?: TourAdvance;
  retreatWhenMissing?: string;
  backTo?: string;
  skipTo?: string;
  keyboardHint?: string;
};

export type TourDefinition = {
  id: string;
  version: number;
  kind: "core" | "guide";
  category: (typeof TOUR_CATEGORIES)[number]["id"];
  title: string;
  description: string;
  duration: string;
  demoGame?: boolean;
  practice?: boolean;
  release?: string;
  nextTourId?: string;
  steps: TourStep[];
};

const a = (name: string) => `[data-tour="${name}"]`;
// Both practice games share the card marker. Keep WoW-specific instructions
// attached to WoW when dragging hides it or a shelf filters it out.
const libraryTourCard = `${a("demo-game-card")}[data-tour-game-id="${TOUR_DEMO_GAME.gameId}"]`;

export const TOURS: TourDefinition[] = [
  {
    id: "core",
    version: 1,
    kind: "core",
    category: "getting-started",
    title: "Quick tour",
    description: "The essentials of PlayCounter in about a minute.",
    duration: "1 min",
    steps: [
      {
        id: "intro",
        view: "keep",
        title: "PlayCounter in 60 seconds",
        body: "PlayCounter runs in the background and records how long you play. It doesn't matter where the game came from: a launcher, a disc, an emulator, or a single .exe file on your desktop.",
      },
      {
        id: "now",
        view: "now",
        anchor: a("now-playing-demo"),
        additionalAnchors: [a("nav-now")],
        cardPlacement: "below",
        title: "Now Playing",
        body: "This is a sample session, not a real one.\n\nThe green Now playing badge and the running timer mean PlayCounter is tracking right now. Total playtime and session count go up while you play.",
      },
      {
        id: "games",
        view: "games",
        anchor: a("core-library-demo"),
        additionalAnchors: [a("nav-games")],
        cardPlacement: "below",
        title: "My Games",
        body: "Every game you play shows up here with cover, total playtime, and session count. These two cards are only samples. Right-click any real card to edit it.",
      },
      {
        id: "history",
        view: "history",
        anchor: a("nav-history"),
        title: "My History",
        body: "Search every past session and explore charts of when and how much you play.",
      },
      {
        id: "achievements",
        view: "achievements",
        anchor: a("nav-achievements"),
        title: "Achievements",
        body: "Local milestones unlock as your hours add up - purely for fun.",
      },
      {
        id: "discovered",
        view: "discovered",
        anchor: a("nav-discovered"),
        title: "Discovered",
        body: "Sort out any app PlayCounter couldn't identify: match it to a game, add it yourself, or ignore it. The badge counts what still needs review.",
      },
      {
        id: "settings",
        view: "settings",
        anchor: a("nav-settings"),
        title: "Settings",
        body: "Tune startup, desktop popups, colors, emulators, backups, and updates.",
      },
      {
        id: "help",
        view: "return",
        anchor: a("help"),
        title: "You're set up",
        body: "Before you start playing, take a minute for Settings: make sure Launch on startup is on, pick the popups you want, and choose your accent color.",
      },
    ],
  },
  {
    id: "notes-playthroughs",
    version: 1,
    kind: "guide",
    category: "library",
    title: "Notes & playthroughs",
    description:
      "Write a note, start a new playthrough, and move a session into it.",
    duration: "3 min",
    practice: true,
    release: "1.1.17",
    nextTourId: "organize-library",
    steps: [
      {
        id: "intro",
        view: "games",
        anchor: a("demo-library-cards"),
        title: "Remember where you left off",
        body: "Every game has a journal: a note, playthroughs, and the sessions that belong to each playthrough. Practice with the sample World of Warcraft card below. Everything you change here is thrown away when the guide ends. Your own games are not touched.",
      },
      {
        id: "open-journal",
        view: "games",
        anchor: libraryTourCard,
        anchorTargets: [a("demo-menu-note")],
        interactive: true,
        allow: [libraryTourCard, a("demo-library-menu")],
        advanceOn: { type: "anchor-present", selector: a("demo-journal") },
        skipTo: "note",
        title: "Right-click World of Warcraft",
        body: "Choose Add note to open the journal. Later you can also open it with Playthroughs in the same menu, or by clicking the note icon on a game's cover.",
        keyboardHint: "Keyboard: focus the card and press Shift+F10.",
      },
      {
        id: "note",
        view: "games",
        anchor: a("demo-note-input"),
        additionalAnchors: [a("demo-note-save")],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [a("demo-journal-note")],
        title: "Write a note for next time",
        body: "Type something like “Finish the Westfall quests, then head to Stormwind.” Click Save note, or simply click somewhere else: the note is saved either way. This note belongs to Default playthrough, the playthrough every game starts with. When you are done, choose Next.",
      },
      {
        id: "create-run",
        view: "games",
        anchor: a("demo-playthrough-name"),
        additionalAnchors: [a("demo-playthrough-create")],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [a("demo-new-playthrough")],
        title: "Start a new playthrough",
        body: "Type a name such as “Speedrun” in the box at the bottom left and press Enter. Each playthrough gets its own note, its own playtime, and its own list of sessions. Everything you played before stays in Default playthrough.",
      },
      {
        id: "active-run",
        view: "games",
        anchor: a("demo-playthrough-active"),
        additionalAnchors: [a("demo-note-input")],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [
          a("demo-playthrough-list"),
          a("demo-playthrough-actions"),
          a("demo-journal-note"),
        ],
        title: "Choose where new sessions go",
        body: "The playthrough marked Active is where your next sessions are counted. A new playthrough becomes active right away. Click any playthrough in the list to look at it, and use Make active to switch. Now write a note just for Speedrun. Each playthrough keeps its own note; the note from Default playthrough is not copied over.",
      },
      {
        id: "move-session",
        view: "games",
        anchor: `${a("demo-playthrough-list")} [role="option"]:last-child`,
        anchorTargets: [
          a("demo-session-named-playthrough"),
          a("demo-session-playthrough"),
        ],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [
          a("demo-playthrough-sessions"),
          a("demo-playthrough-list"),
          a("demo-library-menu"),
        ],
        title: "Move an earlier session into Speedrun",
        body: "We switched to Default playthrough so you can see its sessions. Every session has a playthrough label on the right. Click the label on a sample session and choose Speedrun. The session and its playtime move over, and the game's total stays the same. The same label is available on every session in My History.",
      },
      {
        id: "finish-run",
        view: "games",
        anchor: a("demo-playthrough-finish"),
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [a("demo-playthrough-actions")],
        title: "Finish a playthrough",
        body: "Click Mark finished. The playthrough keeps its note and sessions, so you can look them up any time. If it was the active playthrough, new sessions go back to Default playthrough until you make another one active. Finishing a playthrough does not change the game's progress status; you set that separately.",
      },
      {
        id: "finish",
        view: "games",
        anchor: a("demo-library-cards"),
        title: "See your note when you play",
        body: "When you start one of your own games, Now Playing shows the note of its active playthrough. In Settings → Desktop notifications, turn on Notes in game-start popups to see it in the popup as well. After a session ends, the saved-session popup has an Update note button so you can write down where you stopped. Replay this guide any time from ? Help.",
      },
    ],
  },
  {
    id: "organize-library",
    version: 1,
    kind: "guide",
    category: "library",
    title: "Favorites & shelves",
    description:
      "Mark favorites, build a shelf by hand, and let filters fill one automatically.",
    duration: "3 min",
    practice: true,
    release: "1.1.17",
    nextTourId: "library-progress",
    steps: [
      {
        id: "intro",
        view: "games",
        anchor: a("demo-organization"),
        title: "Make a library that fits you",
        body: "Favorites keep the games you play most within reach. Shelves let you group games any way you like, and a game can sit on several shelves at once. Practice with the sample World of Warcraft and GTA V cards below. Nothing in this practice library is saved.",
      },
      {
        id: "favorite",
        view: "games",
        anchor: a("demo-favorites"),
        anchorTargets: [a("demo-menu-favorite")],
        additionalAnchors: [libraryTourCard],
        interactive: true,
        manualAdvance: true,
        allow: [a("demo-library-stage"), a("demo-library-menu")],
        title: "Keep a favorite close",
        body: "Drag a sample card onto Favorites, or right-click the card and choose Add to Favorites. A star appears on its cover. Click Favorites to see only your favorites, then All games to go back.",
      },
      {
        id: "create-shelf",
        view: "games",
        anchor: a("demo-new-shelf"),
        anchorTargets: [a("demo-shelf-name")],
        additionalAnchors: [a("demo-shelf-save")],
        interactive: true,
        advanceOn: { type: "event", name: "library.demo-shelf-created" },
        skipTo: "fill-shelf",
        allow: [a("demo-organization"), a("demo-library-modal")],
        title: "Create your own shelf",
        body: "Click New shelf, type a name such as “Online Games”, and press Enter. The new shelf starts empty, ready for the games you choose.",
      },
      {
        id: "fill-shelf",
        view: "games",
        anchor: a("demo-personal-shelf"),
        anchorTargets: [
          a("demo-journal-shelf-choice"),
          a("demo-journal-shelf"),
          a("demo-menu-organize"),
        ],
        additionalAnchors: [libraryTourCard],
        interactive: true,
        manualAdvance: true,
        allow: [
          a("demo-library-stage"),
          a("demo-library-menu"),
          a("demo-library-modal"),
        ],
        title: "Put games on your shelf",
        body: "We switched back to All games. Drag a sample card onto your new shelf, then click the shelf to see the game there. Without dragging: right-click a card, choose Shelves & status, then Shelf. While you drag, a shelf that cannot take the game tells you why.",
      },
      {
        id: "filters",
        view: "games",
        anchor: a("demo-filters-toggle"),
        anchorTargets: [a("demo-filter-status-playing")],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [a("demo-organization")],
        title: "Let a shelf fill itself",
        body: "A shelf can also fill itself from filters. We opened Filters for your shelf. Under Progress, choose In progress. The cards below now preview every game in your library with that status; the sample World of Warcraft already has it. You can combine filters for progress, playtime, emulator, and how long a game has not been played.",
      },
      {
        id: "save-filters",
        view: "games",
        anchor: a("demo-filters-toggle"),
        anchorTargets: [
          `${a("demo-save-filters")}:not(:disabled)`,
          a("demo-filtered-shelf"),
        ],
        scrollIntoView: true,
        interactive: true,
        manualAdvance: true,
        allow: [a("demo-organization"), a("demo-library-menu")],
        title: "Save the filters to your shelf",
        body: "Click Save filters. From now on, games join or leave this shelf on their own as they match the filters. To change them later, right-click the shelf and choose Edit filters. Remove saved filters brings back the games you added by hand. A shelf with saved filters does not accept dragged games, and tells you so when you try.",
      },
      {
        id: "finish",
        view: "games",
        anchor: a("demo-organization"),
        title: "My Games remembers your view",
        body: "Your search and the shelf you selected stay in place when you switch to another page and come back. Next up: give several games a progress status at once and choose what their cards show.",
      },
    ],
  },
  {
    id: "library-progress",
    version: 1,
    kind: "guide",
    category: "library",
    title: "Progress & card layout",
    description:
      "Set a progress status for several games at once and choose what game cards show.",
    duration: "3 min",
    practice: true,
    release: "1.1.17",
    steps: [
      {
        id: "intro",
        view: "games",
        anchor: a("demo-library-cards"),
        title: "Track what you want to play next",
        body: "A progress status is your own label for a game: In progress, On hold, Finished, Want to play, and more. It has nothing to do with whether the game is running right now. This guide uses sample cards and temporary settings; your library and preferences stay unchanged.",
      },
      {
        id: "filter",
        view: "games",
        anchor: a("demo-filters-toggle"),
        anchorTargets: [a("demo-filter-status-none")],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [a("demo-organization")],
        title: "Find games without a status",
        body: "We opened Filters. Under Progress, choose No status to show only games that have no status yet. Both sample games start without one. In your own library, narrow the view with search, a shelf, or filters first, so you only select the games you really want to change.",
      },
      {
        id: "select",
        view: "games",
        anchor: a("demo-library-select"),
        interactive: true,
        allow: [a("demo-library-stage")],
        advanceOn: { type: "anchor-present", selector: a("demo-bulk-actions") },
        skipTo: "select-games",
        title: "Turn on selection",
        body: "Click Select. A checkbox appears on every card so you can pick several games at once. The guide continues as soon as selection is on.",
      },
      {
        id: "select-games",
        view: "games",
        anchor: a("demo-library-select"),
        anchorTargets: [
          `${a("demo-library-cards")} [role="checkbox"][aria-checked="false"]`,
          a("demo-bulk-count"),
        ],
        additionalAnchors: [`${a("demo-bulk-select-all")}:not(:disabled)`],
        interactive: true,
        manualAdvance: true,
        allow: [a("demo-library-stage")],
        title: "Select a few games or all of them",
        body: "Click both sample cards to select them; the highlight moves on to the next card that is not selected yet. Shift-click selects everything between two cards. Select all results (or Ctrl/Cmd+A) selects every game in the current view. Changing the search, shelf, or filters clears your selection.",
      },
      {
        id: "apply",
        view: "games",
        anchor: a("demo-library-select"),
        anchorTargets: [
          a("demo-bulk-status-playing"),
          a("demo-bulk-set-status"),
          a("demo-library-result"),
        ],
        interactive: true,
        manualAdvance: true,
        allow: [a("demo-library-stage"), a("demo-library-menu")],
        title: "Set their status together",
        body: "Click Set status and choose In progress. If you skipped the last step, both samples are selected for you. Because the view is filtered to No status, the games disappear from it as soon as they get one. Clear filters shows them again. Clear status in the same menu removes a status.",
      },
      {
        id: "open-customize",
        view: "games",
        anchor: a("demo-customize-toggle"),
        interactive: true,
        allow: [a("demo-library-stage")],
        advanceOn: {
          type: "anchor-present",
          selector: a("demo-library-customize"),
        },
        skipTo: "customize",
        title: "Open the card options",
        body: "Click Customize. This is where you set how many cards fit in a row and which details show on the covers.",
      },
      {
        id: "customize",
        view: "games",
        anchor: a("demo-customize-toggle"),
        anchorTargets: [a("demo-grid-columns")],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [a("demo-library-stage")],
        title: "Choose how many cards fit in a row",
        body: "Move the Cards per row slider. The sample grid starts at five. Fewer cards per row means bigger covers; more cards fit more games on screen. These are the same controls as Customize in My Games, but here they only change the practice library.",
      },
      {
        id: "card-details",
        view: "games",
        anchor: a("demo-customize-toggle"),
        anchorTargets: [a("demo-show-status")],
        additionalAnchors: [a("demo-show-notes"), a("demo-show-shelves")],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [a("demo-library-stage")],
        title: "Choose which details to show",
        body: "Switch Show status on game cards and Show notes on game cards off and on to watch the badges on the sample covers disappear and return. Show shelves hides or shows the whole shelf row above the library. Hiding a badge only changes what you see; your statuses, notes, and shelves are kept.",
      },
      {
        id: "finish",
        view: "games",
        anchor: a("demo-library-cards"),
        title: "Ready for your own library",
        body: "In My Games, use Select to change a batch of games at once, or right-click a single card and choose Shelves & status. Choices you make in the real Customize panel are remembered the next time you open PlayCounter. Everything from this practice disappears when you finish.",
      },
    ],
  },
  {
    id: "launch-games",
    version: 1,
    kind: "guide",
    category: "detection",
    title: "Launch games directly",
    description:
      "Turn on direct launching, see how it works, and try the controller flow.",
    duration: "2 min",
    demoGame: true,
    steps: [
      {
        id: "intro",
        view: "settings",
        anchor: a("settings-launcher"),
        scrollIntoView: true,
        title: "PlayCounter can start games too",
        body: "PlayCounter remembers the game file of every game it recognizes, on this PC only. Direct launching is off by default. Turn it on to get a Play button on every game card in My Games.",
      },
      {
        id: "enable",
        view: "settings",
        anchor: a("settings-launcher"),
        interactive: true,
        manualAdvance: true,
        persistentInteraction: true,
        scrollIntoView: true,
        allow: [a("settings-launcher")],
        title: "Choose whether to enable it",
        body: "The switch is real and saves right away. You can also leave it off and keep following this guide.",
      },
      {
        id: "learned",
        view: "games",
        anchor: a("demo-launch-play"),
        title: "PlayCounter learns launch files locally",
        body: "Start a game the usual way once. From then on, its card in My Games has a Play button that starts the game for you.",
      },
      {
        id: "set-forget",
        view: "games",
        anchor: a("demo-menu-launch-file"),
        retreatWhenMissing: a("demo-context-menu"),
        backTo: "learned",
        title: "Change or forget a launch file",
        body: "Right-click a game to set a different .exe. If a saved file goes missing, PlayCounter quietly removes the broken Play option until you set a new one.",
      },
      {
        id: "limits",
        view: "settings",
        anchor: a("settings-launcher"),
        scrollIntoView: true,
        title: "Some games still need their usual launcher",
        body: "PlayCounter starts the .exe directly, so games that need Steam, Epic, or extra startup steps may only work from their normal launcher.",
      },
      {
        id: "privacy",
        view: "settings",
        anchor: a("settings-launcher"),
        scrollIntoView: true,
        title: "Paths stay on this PC",
        body: "Saved launch paths never leave your device and aren't included in backups. Turn Remember launch paths off to clear them and stop learning new ones without touching your games or history.",
      },
      {
        id: "controller",
        view: "settings",
        anchor: a("settings-launcher"),
        scrollIntoView: true,
        title: "Optional controller navigation",
        body: "Turn on Controller navigation to move around PlayCounter with a controller. To bring PlayCounter to the front, hold Select/View + R1/RB a few seconds and then release.",
      },
    ],
  },
  {
    id: "log-playtime",
    version: 1,
    kind: "guide",
    category: "playtime",
    title: "Log missed playtime",
    description: "Practice adding a session from a game's right-click menu.",
    duration: "2 min",
    demoGame: true,
    steps: [
      {
        id: "intro",
        view: "games",
        title: "Log playtime by hand",
        body: "We'll use a sample World of Warcraft card. Nothing you do here is saved, and your real games can't be changed while the guide runs.",
      },
      {
        id: "open-menu",
        view: "games",
        interactive: true,
        anchor: a("demo-game-card"),
        allow: [a("demo-game-card")],
        advanceOn: {
          type: "anchor-present",
          selector: a("demo-menu-log-session"),
        },
        skipTo: "alternative",
        title: "Right-click the sample card",
        body: "Every game card has a right-click menu with advanced actions.",
      },
      {
        id: "pick-item",
        view: "games",
        interactive: true,
        anchor: a("demo-menu-log-session"),
        allow: [a("demo-context-menu")],
        advanceOn: {
          type: "anchor-present",
          selector: a("demo-log-session-dialog"),
        },
        retreatWhenMissing: a("demo-context-menu"),
        backTo: "open-menu",
        skipTo: "alternative",
        title: "Choose “Log missed session”",
        body: "For a real game, this adds a session to History and updates charts and achievements.",
      },
      {
        id: "fill-dialog",
        view: "games",
        interactive: true,
        anchor: a("demo-log-session-dialog"),
        allow: [a("demo-log-session-backdrop")],
        advanceOn: { type: "event", name: "mygames.demo-session-logged" },
        retreatWhenMissing: a("demo-log-session-dialog"),
        backTo: "open-menu",
        skipTo: "alternative",
        title: "Enter length and end time",
        body: "Choose how long you played and when the session ended, then press Log session.",
      },
      {
        id: "result",
        view: "games",
        anchor: a("demo-playtime-result"),
        backTo: "open-menu",
        title: "Playtime and session updated",
        body: "The duration you entered was added to the game's total playtime, and one new session was created. For a real game, that session also appears in History and contributes to charts and achievements.",
      },
      {
        id: "alternative",
        view: "games",
        anchor: a("demo-menu-adjust-playtime"),
        backTo: "open-menu",
        title: "Only know a total?",
        body: "Use Adjust total playtime instead when you only know a lifetime total. It corrects the number without inventing history entries. You're now ready to try either option on one of your own games.",
      },
    ],
  },
  {
    id: "game-actions",
    version: 2,
    kind: "guide",
    category: "library",
    title: "Manage a game in your library",
    description: "Everything in a game's right-click menu.",
    duration: "2 min",
    demoGame: true,
    steps: [
      {
        id: "intro",
        view: "games",
        anchor: a("demo-game-card"),
        title: "More actions for every game",
        body: "Every card in My Games has a right-click menu. It's where you fix playtime, correct a wrong match, or get rid of a game.\n\nWe'll use a sample card, so nothing in your library can change.",
      },
      {
        id: "open-menu",
        view: "games",
        interactive: true,
        anchor: a("demo-game-card"),
        allow: [a("demo-game-card")],
        advanceOn: {
          type: "anchor-present",
          selector: a("demo-menu-show-history"),
        },
        skipTo: "history",
        title: "Right-click the sample card",
        body: "Which items you get depends on where the game came from. This sample is a community match, so you see what a matched game offers. A game you added yourself has a few different items.",
      },
      {
        id: "history",
        view: "games",
        anchor: a("demo-menu-show-history"),
        retreatWhenMissing: a("demo-context-menu"),
        backTo: "open-menu",
        title: "See only this game's sessions",
        body: "Show History jumps to My History with this game already filtered. Nothing is changed - it's just a different view.",
      },
      {
        id: "playtime",
        view: "games",
        anchor: a("demo-menu-log-session"),
        additionalAnchors: [a("demo-menu-adjust-playtime")],
        retreatWhenMissing: a("demo-context-menu"),
        backTo: "open-menu",
        title: "Add playtime that's missing",
        body: "Log missed session adds one session with the date and length you enter. Adjust total playtime changes only the lifetime number - useful when you carry a total over from a launcher.",
      },
      {
        id: "matches",
        view: "games",
        anchor: a("demo-menu-check-matches"),
        retreatWhenMissing: a("demo-context-menu"),
        backTo: "open-menu",
        title: "Look the game up again",
        body: "'Check for Matches' searches IGDB and the Community database for this file name one more time. Worth trying when a game wasn't found before - a match may have been added since, and a custom game can turn into a real one.",
      },
      {
        id: "wrong-match",
        view: "games",
        anchor: a("demo-menu-report-match"),
        additionalAnchors: [a("demo-menu-convert-custom")],
        retreatWhenMissing: a("demo-context-menu"),
        backTo: "open-menu",
        title: "Fix a wrong match",
        body: "Report Wrong Match asks what the app really is - a different game, or no game at all - and sends that in for review. Convert to Custom Game keeps it here under a name you pick yourself.",
      },
      {
        id: "remove",
        view: "games",
        anchor: a("demo-menu-remove"),
        retreatWhenMissing: a("demo-context-menu"),
        backTo: "open-menu",
        title: "Remove is not the same as ignore",
        body: "Remove from Library takes the game out of My Games and asks whether to keep its sessions. It comes back the next time you play it.\n\nIgnore Game does the same, and blocks the file on top - so PlayCounter never picks it up again.",
      },
    ],
  },
  {
    id: "fix-detection",
    version: 1,
    kind: "guide",
    category: "detection",
    title: "Fix an unrecognized game",
    description: "Review and match an app PlayCounter found.",
    duration: "1 min",
    steps: [
      {
        id: "intro",
        view: "discovered",
        title: "When a game isn't recognized",
        body: "Sometimes PlayCounter needs your help: a file name it has never seen, or one that several games share. We'll use a sample Wow.exe so you can walk through the whole flow without changing your data.",
      },
      {
        id: "filters",
        view: "discovered",
        anchor: a("discovered-filters"),
        title: "Start with Needs review",
        body: "This filter lists apps PlayCounter saw but could not identify. Tracked and Ignored show the rest.",
      },
      {
        id: "wizard",
        view: "discovered",
        anchor: a("discovered-wizard"),
        title: "Discovery Wizard",
        body: "The wizard goes through everything PlayCounter found but couldn't identify - one app at a time.\n\nYou get the file name (here Wow.exe) and whether it's running right now. That's usually enough to answer one question: is this a game?",
      },
      {
        id: "add-share",
        view: "discovered",
        anchor: a("discovered-add-share"),
        title: "Add & Share",
        body: "Pick this when it's a real game. Everything listed in Discovered is a file PlayCounter doesn't know yet. Click the button, find the right game in the database and send it in. Once it's approved, everyone's PlayCounter recognizes this file automatically.",
      },
      {
        id: "add-custom",
        view: "discovered",
        anchor: a("discovered-add-custom"),
        title: "Add as Custom",
        body: "Keep the game on this PC only. Best for private builds, mods, prototypes, and anything else that shouldn't become a match for everyone.",
      },
      {
        id: "ignore",
        view: "discovered",
        anchor: a("discovered-ignore"),
        title: "Ignore",
        body: "Use this for launchers, updaters, tools, and anything else that isn't a game. PlayCounter stops asking about it and never tracks it.",
      },
      {
        id: "skip",
        view: "discovered",
        anchor: a("discovered-skip"),
        title: "Skip for now",
        body: "Not sure yet? Leave it open. It stays in Needs review so you can decide later.",
      },
      {
        id: "ambiguous",
        view: "now",
        anchor: a("nav-now"),
        title: "When one name fits several games",
        body: "When a file name could belong to several games, Now Playing asks which one you started. That happens when different games ship a program file with the same name.",
      },
    ],
  },
  {
    id: "stats",
    version: 1,
    kind: "guide",
    category: "playtime",
    title: "Read your stats",
    description: "Explore sessions, charts, and milestones.",
    duration: "1 min",
    steps: [
      {
        id: "intro",
        view: "history",
        title: "Your play history",
        body: "Every completed session becomes part of a searchable timeline.",
      },
      {
        id: "sessions",
        view: "history",
        anchor: a("history-toolbar"),
        title: "Find a session",
        body: "Use search and filters to narrow the timeline, then open a game or session for details.",
      },
      {
        id: "charts",
        view: "history",
        anchor: a("history-playtime-chart"),
        title: "See your patterns",
        body: "Playtime over time is your first overview. More charts below reveal your top games, busiest days, and how your habits change.",
      },
      {
        id: "milestones",
        view: "achievements",
        anchor: a("nav-achievements"),
        title: "Track milestones",
        body: "Achievements show what you've unlocked and progress toward what comes next.",
      },
    ],
  },
  {
    id: "settings",
    version: 1,
    kind: "guide",
    category: "settings",
    title: "Personalize PlayCounter",
    description: "Walk through key settings and adjust them as you go.",
    duration: "2 min",
    steps: [
      {
        id: "intro",
        view: "settings",
        title: "Settings, your way",
        body: "This guide walks through the most useful preferences. Controls inside each highlighted panel stay active, and any changes you make are real and saved immediately.",
      },
      {
        id: "general",
        view: "settings",
        anchor: a("settings-general"),
        interactive: true,
        manualAdvance: true,
        persistentInteraction: true,
        scrollIntoView: true,
        allow: [a("settings-general")],
        title: "General behavior",
        body: "Leave Launch on startup on. PlayCounter can only track while it's running - if it doesn't start with your PC, you lose the playtime of every game you start before opening it.\n\nBelow that you can switch long playtimes to days and hours.",
      },
      {
        id: "appearance",
        view: "settings",
        anchor: a("settings-appearance"),
        interactive: true,
        manualAdvance: true,
        persistentInteraction: true,
        scrollIntoView: true,
        allow: [a("settings-appearance")],
        title: "Choose your accent",
        body: "Pick the accent color used for buttons, highlights, and focus states. Try a color now, or use Reset to return to the PlayCounter default.",
      },
      {
        id: "notifications",
        view: "settings",
        anchor: a("settings-notifications"),
        optional: true,
        interactive: true,
        manualAdvance: true,
        persistentInteraction: true,
        scrollIntoView: true,
        allow: [a("settings-notifications")],
        title: "Desktop popups",
        body: "Short popups on your desktop while you play. Turn the main switch on first, then pick which events are worth a popup: first-time detections, every game start, session summaries, milestones, or new discoveries.",
      },
      {
        id: "sharing",
        view: "settings",
        anchor: a("settings-sharing"),
        interactive: true,
        manualAdvance: true,
        persistentInteraction: true,
        scrollIntoView: true,
        allow: [a("settings-sharing")],
        title: "Help improve detection",
        body: "When you ignore an app PlayCounter doesn't recognize, it sends the file name, your platform, and an anonymous install ID to improve PlayCounter. Playtime and game history are never shared.",
      },
      {
        id: "updates",
        view: "settings",
        anchor: a("settings-updates"),
        scrollIntoView: true,
        title: "Keep PlayCounter current",
        body: "Click Check for updates whenever you like. This panel shows which version you are running, whether a new one is available, and the release notes.",
      },
    ],
  },
  {
    id: "backup-data",
    version: 2,
    release: "1.1.17",
    kind: "guide",
    category: "settings",
    title: "Back up or move your data",
    description:
      "Automatic backups, export, and restoring your data on another PC.",
    duration: "1 min",
    steps: [
      {
        id: "intro",
        view: "settings",
        title: "Your data stays portable",
        body: "Open Settings and find Backup & transfer whenever you want to protect your local data or move PlayCounter to another PC. This guide explains both actions without opening a file dialog or changing your data.",
      },
      {
        id: "overview",
        view: "settings",
        anchor: a("settings-backup"),
        scrollIntoView: true,
        title: "Backup & transfer",
        body: "A backup is a single JSON file. It contains your play history, your games, your notes, playthroughs, shelves, and app settings. Saved launch paths are not included; they stay on this PC.",
      },
      {
        id: "automatic",
        view: "settings",
        anchor: a("settings-backup-enabled"),
        scrollIntoView: true,
        title: "Automatic backups",
        body: "PlayCounter saves a backup once a week and keeps the last five. If a backup was missed because PlayCounter was not running, it is saved the next time you open the app. This guide only points at the controls; it does not change your settings or create a backup.",
      },
      {
        id: "schedule",
        view: "settings",
        anchor: a("settings-backup-interval"),
        additionalAnchors: [
          a("settings-backup-keep"),
          a("settings-backup-now"),
        ],
        scrollIntoView: true,
        title: "Choose how often, and how many to keep",
        body: "Schedule switches between daily and weekly backups. Keep sets how many backups stay on disk; once the limit is reached, the oldest automatic backup is deleted. Back up now saves a backup right away.",
      },
      {
        id: "folder",
        view: "settings",
        anchor: a("settings-backup-choose-folder"),
        additionalAnchors: [a("settings-backup-open-folder")],
        scrollIntoView: true,
        title: "Know where your backups are",
        body: "Automatic backups go to PlayCounter's app data folder unless you pick another one with Choose folder. Open folder shows the files. For extra safety, pick a folder that is synced to the cloud or included in your own backups.",
      },
      {
        id: "export",
        view: "settings",
        anchor: a("settings-backup-export"),
        scrollIntoView: true,
        title: "Export your data",
        body: "Choose Export to save the current local data as a JSON file. Keep that file somewhere safe or copy it to the PC where you want to continue using PlayCounter.",
      },
      {
        id: "import",
        view: "settings",
        anchor: a("settings-backup-import"),
        scrollIntoView: true,
        title: "Import a backup",
        body: "Choose Import and select a PlayCounter backup file. Import replaces the current local data; PlayCounter automatically creates a safety backup of the current state first. The button stays locked during this guide to avoid an accidental import.",
      },
    ],
  },
  {
    id: "feedback-replies",
    version: 1,
    kind: "guide",
    category: "settings",
    release: "1.1.17",
    title: "Find replies to your feedback",
    description: "See where replies to your feedback show up.",
    duration: "30 sec",
    steps: [
      {
        id: "send",
        view: "keep",
        anchor: a("send-feedback"),
        title: "Report a bug or suggest a feature",
        body: "Use Send feedback to report a bug, ask a question, or suggest a feature. When we answer, the reply shows up right here in PlayCounter. This guide shows a sample reply and does not send anything.",
      },
      {
        id: "bell",
        view: "keep",
        anchor: a("demo-feedback-notification"),
        positionAnchor: a("demo-feedback-panel"),
        additionalAnchors: [a("notifications-bell")],
        title: "Replies appear under the bell",
        body: "Replies show up in Notifications, together with other PlayCounter updates. This one is a sample; your real notifications and unread count are not changed.",
      },
      {
        id: "context",
        view: "keep",
        anchor: a("demo-feedback-original"),
        positionAnchor: a("demo-feedback-panel"),
        additionalAnchors: [a("demo-feedback-reply")],
        title: "Your message stays with the answer",
        body: "Your own message is quoted above the reply, so you always know what the answer is about. Replies are delivered to the PlayCounter installation that sent the feedback, so check the bell on this PC after you send something.",
      },
    ],
  },
  {
    id: "emulators",
    version: 3,
    release: "1.1.17",
    kind: "guide",
    category: "detection",
    title: "Track emulator games",
    description:
      "Learn how PlayCounter detects games running inside emulators.",
    duration: "2 min",
    steps: [
      {
        id: "intro",
        view: "settings",
        title: "Games inside emulators",
        body: "PlayCounter can tell which game is running inside a supported emulator, instead of just logging the emulator itself.\n\nSupported right now:\n\n- Dolphin\n- DOSBox\n- PCSX2\n\nMissing one? Ask for it via the Feedback button or on Discord.\n\nThis guide uses a sample Dolphin setup. Nothing here is real: no sample can be changed, shared, or deleted, and every button on it is switched off.",
      },
      {
        id: "settings",
        view: "settings",
        anchor: a("settings-emulators"),
        scrollIntoView: true,
        title: "Enable emulator detection",
        body: "Turn emulator detection on here. PlayCounter reads the loaded game file, the window title, and the start-up options of the emulator on your PC to work out which game is running. Only the recognized game name or disc ID is sent to the database - never the full path or the window title.\n\nEvery emulator PlayCounter has already seen is listed below the switches. That's also where you can ignore one again.",
      },
      {
        id: "menu",
        view: "keep",
        anchor: a("nav-emulators"),
        title: "Two kinds of entry in this section",
        body: "Dolphin, DOSBox, and any other emulator page is added the first time PlayCounter sees that emulator running on your PC - and then it stays, whether or not anything is running. On a fresh install you won't find one here yet.\n\nNow Emulating works differently: it appears while an emulator is actually running. If the emulator stops while you are on that view, it stays in the menu until you leave it.\n\nThe whole section is hidden while emulator detection is off, or while every emulator you've seen is ignored. For this guide we're showing a Dolphin example, even if you have never started it.",
      },
      {
        id: "now-emulating",
        view: "emulating",
        anchor: a("demo-emulator-now"),
        additionalAnchors: [a("nav-emulating")],
        cardPlacement: "below",
        title: "Now Emulating: what's running right now",
        body: "This is a sample session, not a real one.\n\nNow Emulating is the live view. It shows the game currently loaded in your emulator, with a running timer and a badge for the emulator and the file it came from.\n\nIt normally only appears while something is running. If PlayCounter can't tell which game is loaded, it asks you right here and you pick the game once.",
      },
      {
        id: "emulator-page",
        view: "dolphin",
        anchor: a("nav-dolphin"),
        title: "The Dolphin page stays",
        body: "PlayCounter added this page the first time it saw Dolphin running, and it stays in the menu from then on - nothing has to be running to open it.\n\nThis is where that emulator's playtime, its sessions, and all of its game matches live.",
      },
      {
        id: "linked-games",
        view: "dolphin",
        anchor: a("demo-emulator-linked"),
        cardPlacement: "below",
        title: "Your linked games",
        body: "One row per game PlayCounter connected to a file or disc ID inside Dolphin. This row is a sample. Once a game is linked, PlayCounter recognizes it automatically every time you start it - you normally do not need to choose the game again.",
      },
      {
        id: "confirm",
        view: "dolphin",
        anchor: a("demo-emulator-confirm"),
        additionalAnchors: [a("demo-emulator-check-badge")],
        title: "Check this once",
        body: "When PlayCounter matches a game automatically, check whether the game name it found is the game you just started. If it is, press Looks right and the note disappears.\n\nOn the sample the button is switched off - try it on your own games later.",
      },
      {
        id: "fix-match",
        view: "dolphin",
        anchor: a("demo-emulator-actions"),
        title: "Correct, drop, or share a match",
        body: "Change game replaces a wrong match - search once and it sticks. Forget game makes PlayCounter ask again the next time that game shows up; recorded playtime stays in History. Share match sends the file-to-game link to the Community database, so other people's PlayCounter recognizes it too.\n\nAll three are switched off on this sample row, so nothing can be changed, shared, or deleted while you're here.",
      },
      {
        id: "pcsx2",
        view: "settings",
        anchor: a("settings-emulators"),
        scrollIntoView: true,
        title: "PlayStation 2 games with PCSX2",
        body: "On Windows, turn on emulator detection and start a game in PCSX2. PlayCounter recognizes which PS2 game is loaded and records its sessions under that game, not under PCSX2. The PCSX2 page appears in the menu after PlayCounter has seen the emulator once. If direct launching is on and PlayCounter has learned the game file, you can start the game again from My Games or the PCSX2 page.",
      },
      {
        id: "library",
        view: "games",
        anchor: a("nav-games"),
        title: "One shared library",
        body: "Completed emulator sessions appear in My Games and History alongside native PC games, with an emulator badge showing where they came from.",
      },
    ],
  },
  {
    id: "source-badges",
    version: 1,
    kind: "guide",
    category: "detection",
    title: "Understand game badges",
    description: "Learn how PlayCounter recognized each of your games.",
    duration: "1 min",
    demoGame: true,
    steps: [
      {
        id: "intro",
        view: "games",
        title: "How was this game recognized?",
        body: "A badge tells you how PlayCounter connected the file you started to a game. There are three ways, and we'll show all of them on this sample card - nothing is added to your library.",
      },
      {
        id: "community",
        view: "games",
        anchor: a("demo-source-community"),
        title: "Community",
        body: "The PlayCounter community database links file names to the right games. You can share a match that's missing - once it's reviewed and approved, everyone's PlayCounter recognizes that file automatically.",
      },
      {
        id: "igdb",
        view: "games",
        anchor: a("demo-source-igdb"),
        title: "IGDB",
        body: "IGDB is a large public game database. Some of its entries record the name of the game's .exe file - bg3.exe for Baldur's Gate 3, for example. When it's there, PlayCounter finds the game right away.\n\nPlenty of entries don't have it, though. That's the gap the Community database fills.",
      },
      {
        id: "custom",
        view: "games",
        anchor: a("demo-source-custom"),
        title: "Custom",
        body: "You added this game yourself. The name and the file it points to stay on this PC, unless you send it to the Community database later.",
      },
    ],
  },
];

export const CORE_TOUR_ID = "core";
export const findTour = (id: string) => TOURS.find((tour) => tour.id === id);
export const guideTours = () => TOURS.filter((tour) => tour.kind === "guide");
