import type { ViewId } from "../../store";
import { TOUR_DEMO_GAME } from "./tourDemoGame";

export type TourAdvance =
  | { type: "anchor-present"; selector: string }
  | {
      type: "event";
      name:
        | "demo.action-completed"
        | "mygames.demo-session-logged"
        | "mygames.demo-launch-attempted"
        | "library.demo-shelf-created";
    };

export type TourEventName = Extract<TourAdvance, { type: "event" }>["name"];

export const TOUR_CATEGORIES = [
  { id: "getting-started", title: "Getting started" },
  { id: "library", title: "Your library" },
  { id: "playtime", title: "Playtime & stats" },
  { id: "detection", title: "Detection & launching" },
  { id: "settings", title: "Settings & support" },
] as const;

export type TourStep = {
  id: string;
  title: string;
  body: string;
  view: ViewId | "keep" | "return";
  anchor?: string;
  /** Prefer these targets, in order, as an action opens a menu or dialog. */
  anchorTargets?: string[];
  additionalAnchors?: string[];
  /** Place instructions outside this container while highlighting its detail. */
  positionAnchor?: string;
  cardPlacement?: "below";
  optional?: boolean;
  interactive?: boolean;
  manualAdvance?: boolean;
  persistentInteraction?: boolean;
  scrollIntoView?: boolean;
  allow?: string[];
  advanceOn?: TourAdvance;
  retreatWhenMissing?: string;
  backTo?: string;
  skipTo?: string;
  keyboardHint?: string;
};

export type TourDefinition = {
  id: string;
  version: number;
  kind: "core" | "guide";
  category: (typeof TOUR_CATEGORIES)[number]["id"];
  title: string;
  description: string;
  duration: string;
  demoGame?: boolean;
  practice?: boolean;
  simulation?: "detection" | "stats" | "import";
  finishView?: ViewId;
  release?: string;
  nextTourId?: string;
  steps: TourStep[];
};

const a = (name: string) => `[data-tour="${name}"]`;
// Both practice games share the card marker. Keep WoW-specific instructions
// attached to WoW when dragging hides it or a shelf filters it out.
const libraryTourCard = `${a("demo-game-card")}[data-tour-game-id="${TOUR_DEMO_GAME.gameId}"]`;

export const TOURS: TourDefinition[] = [
  {
    id: "core",
    version: 2,
    kind: "core",
    category: "getting-started",
    title: "Quick tour",
    description: "The essentials of PlayCounter in about a minute.",
    duration: "1 min",
    steps: [
      {
        id: "intro",
        view: "keep",
        title: "PlayCounter in 60 seconds",
        body: "PlayCounter runs in the background and records how long you play. It doesn't matter where the game came from: a launcher, a disc, an emulator, or a single .exe file on your desktop.",
      },
      {
        id: "now",
        view: "now",
        anchor: a("now-playing-demo"),
        additionalAnchors: [a("nav-now")],
        cardPlacement: "below",
        title: "Now Playing",
        body: "This is a sample session, not a real one.\n\nThe green Now playing badge and the running timer mean PlayCounter is tracking right now. The timer and total playtime increase while you play. The session count records separate play sessions.",
      },
      {
        id: "games",
        view: "games",
        anchor: a("core-library-demo"),
        additionalAnchors: [a("nav-games")],
        cardPlacement: "below",
        title: "My Games",
        body: "Every game you play shows up here with cover, total playtime, and session count. These two cards are only samples. Right-click any real card to edit it.",
      },
      {
        id: "history",
        view: "history",
        anchor: a("nav-history"),
        title: "My History",
        body: "Search every past session and explore charts of when and how much you play.",
      },
      {
        id: "achievements",
        view: "achievements",
        anchor: a("nav-achievements"),
        title: "Achievements",
        body: "Local milestones unlock as your hours add up - purely for fun.",
      },
      {
        id: "discovered",
        view: "discovered",
        anchor: a("nav-discovered"),
        title: "Discovered",
        body: "Sort out any app PlayCounter couldn't identify: match it to a game, add it yourself, or ignore it. The badge counts what still needs review.",
      },
      {
        id: "settings",
        view: "settings",
        anchor: a("nav-settings"),
        title: "Settings",
        body: "Tune startup, desktop popups, colors, emulators, backups, and updates.",
      },
      {
        id: "help",
        view: "return",
        anchor: a("help"),
        title: "You're set up",
        body: "Before you start playing, take a minute for Settings: make sure Launch on startup is on, pick the popups you want, and choose your accent color.",
      },
    ],
  },
  {
    id: "notes-playthroughs",
    version: 2,
    kind: "guide",
    category: "library",
    title: "Notes & playthroughs",
    description:
      "Write a note, start a new playthrough, and move a session into it.",
    duration: "3 min",
    practice: true,
    finishView: "games",
    release: "1.1.17",
    nextTourId: "organize-library",
    steps: [
      {
        id: "intro",
        view: "games",
        anchor: a("demo-library-cards"),
        title: "Remember where you left off",
        body: "Every game has a journal: a note, playthroughs, and the sessions that belong to each playthrough. Practice with the sample World of Warcraft card below. Everything you change here is thrown away when the guide ends. Your own games are not touched.",
      },
      {
        id: "open-journal",
        view: "games",
        anchor: libraryTourCard,
        anchorTargets: [a("demo-menu-note")],
        interactive: true,
        allow: [libraryTourCard, a("demo-library-menu")],
        advanceOn: { type: "anchor-present", selector: a("demo-journal") },
        skipTo: "note",
        title: "Right-click World of Warcraft",
        body: "Choose Add note to open the journal. Later you can also open it with Playthroughs in the same menu, or by clicking the note icon on a game's cover.",
        keyboardHint: "Keyboard: focus the card and press Shift+F10.",
      },
      {
        id: "note",
        view: "games",
        anchor: a("demo-note-input"),
        additionalAnchors: [a("demo-note-save")],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [a("demo-journal-note")],
        title: "Write a note for next time",
        body: "Type something like “Finish the Westfall quests, then head to Stormwind.” Click Save note, or simply click somewhere else: the note is saved either way. This note belongs to Default playthrough, the playthrough every game starts with. When you are done, choose Next.",
      },
      {
        id: "create-run",
        view: "games",
        anchor: a("demo-playthrough-name"),
        additionalAnchors: [a("demo-playthrough-create")],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [a("demo-new-playthrough")],
        title: "Start a new playthrough",
        body: "Click Add playthrough under the list, type a name such as “Speedrun” and press Enter. Each playthrough gets its own note, its own playtime, and its own list of sessions. Everything you played before stays in Default playthrough.",
      },
      {
        id: "active-run",
        view: "games",
        anchor: a("demo-playthrough-active"),
        additionalAnchors: [a("demo-note-input")],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [
          a("demo-playthrough-list"),
          a("demo-playthrough-actions"),
          a("demo-journal-note"),
        ],
        title: "Choose where new sessions go",
        body: "The playthrough marked Active is where your next sessions are counted. A new playthrough becomes active right away. Click any playthrough in the list to look at it, and use Make active to switch. Now write a note for your new playthrough. Each playthrough keeps its own note; the note from Default playthrough is not copied over.",
      },
      {
        id: "move-session",
        view: "games",
        anchor: `${a("demo-playthrough-list")} [role="option"]:last-child`,
        anchorTargets: [
          a("demo-session-named-playthrough"),
          a("demo-session-playthrough"),
        ],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [
          a("demo-playthrough-sessions"),
          a("demo-playthrough-list"),
          a("demo-library-menu"),
        ],
        title: "Move an earlier session into your new playthrough",
        body: "We switched to Default playthrough so you can see its sessions. Every session has a playthrough label on the right. Click the label on a sample session and choose the playthrough you created. The session and its playtime move over, and the game's total stays the same. The same label is available on every session in My History.",
      },
      {
        id: "finish-run",
        view: "games",
        anchor: a("demo-playthrough-actions"),
        anchorTargets: [a("demo-playthrough-finish")],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [a("demo-playthrough-actions")],
        title: "Finish a playthrough",
        body: "Click Mark finished. The playthrough keeps its note and sessions, so you can look them up any time. If it was the active playthrough, new sessions go back to Default playthrough until you make another one active. Finishing a playthrough does not change the game's progress status; you set that separately.",
      },
      {
        id: "popups",
        view: "games",
        anchor: a("demo-popup-preview"),
        anchorTargets: [a("demo-note-input")],
        interactive: true,
        manualAdvance: true,
        allow: [a("demo-library-stage"), a("demo-library-modal")],
        title: "Preview your note in desktop popups",
        body: "Turn on Notes in game-start popups to preview the active playthrough's note. Playthrough names is a separate switch. Choose Session saved, enable Update note in popups, and try the button. It opens the sample journal so you can save a reminder. All three real preferences are independent and off by default.",
      },
      {
        id: "finish",
        view: "games",
        anchor: a("demo-library-cards"),
        title: "Use notes in your own games",
        body: "When you start one of your own games, Now Playing shows the note of its active playthrough. In Settings → Desktop popups, turn on Notes in game-start popups to see it in the popup as well. Turn on Update note in popups to add a button to saved-session popups so you can write down where you stopped. Both options are off by default. Replay this guide any time from ? Help.",
      },
    ],
  },
  {
    id: "organize-library",
    version: 2,
    kind: "guide",
    category: "library",
    title: "Favorites & shelves",
    description:
      "Mark favorites, build a shelf by hand, and let filters fill one automatically.",
    duration: "3 min",
    practice: true,
    finishView: "games",
    release: "1.1.17",
    nextTourId: "library-progress",
    steps: [
      {
        id: "intro",
        view: "games",
        anchor: a("demo-organization"),
        title: "Make a library that fits you",
        body: "Favorites keep the games you play most within reach. Shelves let you group games any way you like, and a game can sit on several shelves at once. Practice with the sample World of Warcraft and GTA V cards below. Nothing in this practice library is saved.",
      },
      {
        id: "favorite",
        view: "games",
        anchor: a("demo-favorites"),
        anchorTargets: [a("demo-menu-favorite")],
        additionalAnchors: [libraryTourCard],
        interactive: true,
        manualAdvance: true,
        allow: [a("demo-library-stage"), a("demo-library-menu")],
        title: "Keep a favorite close",
        body: "Drag a sample card onto Favorites, or right-click the card and choose Add to Favorites. A star appears on its cover. Click Favorites to see only your favorites, then All games to go back.",
      },
      {
        id: "create-shelf",
        view: "games",
        anchor: a("demo-new-shelf"),
        anchorTargets: [a("demo-shelf-name")],
        additionalAnchors: [a("demo-shelf-save")],
        interactive: true,
        advanceOn: { type: "event", name: "library.demo-shelf-created" },
        skipTo: "fill-shelf",
        allow: [a("demo-organization"), a("demo-library-modal")],
        title: "Create your own shelf",
        body: "Click New shelf, type a name such as “Online Games”, and press Enter. The new shelf starts empty, ready for the games you choose.",
      },
      {
        id: "fill-shelf",
        view: "games",
        anchor: a("demo-personal-shelf"),
        anchorTargets: [
          a("demo-journal-shelf-choice"),
          a("demo-journal-shelf"),
          a("demo-menu-organize"),
        ],
        additionalAnchors: [libraryTourCard],
        interactive: true,
        manualAdvance: true,
        allow: [
          a("demo-library-stage"),
          a("demo-library-menu"),
          a("demo-library-modal"),
        ],
        title: "Put games on your shelf",
        body: "We switched back to All games. Drag a sample card onto your new shelf, then click the shelf to see the game there. Without dragging: right-click a card, choose Shelves & status, then Add to shelf. While you drag, a shelf that cannot take the game tells you why.",
      },
      {
        id: "filters",
        view: "games",
        anchor: a("demo-filters-toggle"),
        anchorTargets: [a("demo-filter-status-playing")],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [a("demo-organization")],
        title: "Let a shelf fill itself",
        body: "A shelf can also fill itself from filters. We opened Filters for your shelf. Under Progress, choose In progress. The cards below now preview every game in your library with that status; the sample World of Warcraft already has it. You can combine filters for progress, playtime, emulator, and how long a game has not been played.",
      },
      {
        id: "save-filters",
        view: "games",
        anchor: a("demo-filters-toggle"),
        anchorTargets: [
          `${a("demo-save-filters")}:not(:disabled)`,
          a("demo-filtered-shelf"),
        ],
        scrollIntoView: true,
        interactive: true,
        manualAdvance: true,
        allow: [a("demo-organization"), a("demo-library-menu")],
        title: "Save the filters to your shelf",
        body: "Click Save filters. From now on, games join or leave this shelf on their own as they match the filters. To change them later, right-click the shelf and choose Edit filters. Remove saved filters brings back the games you added by hand. A shelf with saved filters does not accept dragged games, and tells you so when you try.",
      },
      {
        id: "finish",
        view: "games",
        anchor: a("demo-organization"),
        title: "My Games remembers your view",
        body: "Your search and the shelf you selected stay in place when you switch to another page and come back. Next up: give several games a progress status at once and choose what their cards show.",
      },
    ],
  },
  {
    id: "library-progress",
    version: 2,
    kind: "guide",
    category: "library",
    title: "Progress & card layout",
    description:
      "Set a progress status for several games at once and choose what game cards show.",
    duration: "3 min",
    practice: true,
    finishView: "games",
    release: "1.1.17",
    steps: [
      {
        id: "intro",
        view: "games",
        anchor: a("demo-library-cards"),
        title: "Track what you want to play next",
        body: "A progress status is your own label for a game: In progress, On hold, Finished, Want to play, and more. It has nothing to do with whether the game is running right now. This guide uses sample cards and temporary settings; your library and preferences stay unchanged.",
      },
      {
        id: "filter",
        view: "games",
        anchor: a("demo-filters-toggle"),
        anchorTargets: [a("demo-filter-status-none")],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [a("demo-organization")],
        title: "Find games without a status",
        body: "We opened Filters. Under Progress, choose No status to show only games that have no status yet. Both sample games start without one. In your own library, narrow the view with search, a shelf, or filters first, so you only select the games you really want to change.",
      },
      {
        id: "select",
        view: "games",
        anchor: a("demo-library-select"),
        interactive: true,
        allow: [a("demo-library-stage")],
        advanceOn: { type: "anchor-present", selector: a("demo-bulk-actions") },
        skipTo: "select-games",
        title: "Turn on selection",
        body: "Click Select. A checkbox appears on every card so you can pick several games at once. The guide continues as soon as selection is on.",
      },
      {
        id: "select-games",
        view: "games",
        anchor: a("demo-library-select"),
        anchorTargets: [
          `${a("demo-library-cards")} [role="checkbox"][aria-checked="false"]`,
          a("demo-bulk-count"),
        ],
        additionalAnchors: [`${a("demo-bulk-select-all")}:not(:disabled)`],
        interactive: true,
        manualAdvance: true,
        allow: [a("demo-library-stage")],
        title: "Select a few games or all of them",
        body: "Click both sample cards to select them; the highlight moves on to the next card that is not selected yet. Shift-click selects everything between two cards. Select all results (or Ctrl/Cmd+A) selects every game in the current view. Changing the search, shelf, or filters clears your selection.",
      },
      {
        id: "apply",
        view: "games",
        anchor: a("demo-library-select"),
        anchorTargets: [
          a("demo-bulk-status-playing"),
          a("demo-bulk-set-status"),
          a("demo-library-result"),
        ],
        interactive: true,
        manualAdvance: true,
        allow: [a("demo-library-stage"), a("demo-library-menu")],
        title: "Set their status together",
        body: "Click Set status and choose In progress. If you skipped the last step, both samples are selected for you. Because the view is filtered to No status, the games disappear from it as soon as they get one. Clear filters shows them again. Clear status removes the status from the selected games. Clear filters only changes which games you see.",
      },
      {
        id: "open-customize",
        view: "games",
        anchor: a("demo-customize-toggle"),
        interactive: true,
        allow: [a("demo-library-stage")],
        advanceOn: {
          type: "anchor-present",
          selector: a("demo-library-customize"),
        },
        skipTo: "customize",
        title: "Open the card options",
        body: "Click Customize. This is where you set how many cards fit in a row and which details show on the covers.",
      },
      {
        id: "customize",
        view: "games",
        anchor: a("demo-customize-toggle"),
        anchorTargets: [a("demo-grid-columns")],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [a("demo-library-stage")],
        title: "Choose how many cards fit in a row",
        body: "Move the Cards per row slider. The sample grid starts at three, with fewer columns in small windows. Fewer cards per row means bigger covers; more cards fit more games on screen. These are the same controls as Customize in My Games, but here they only change the practice library.",
      },
      {
        id: "card-details",
        view: "games",
        anchor: a("demo-customize-toggle"),
        anchorTargets: [a("demo-show-status")],
        additionalAnchors: [a("demo-show-notes"), a("demo-show-shelves")],
        interactive: true,
        manualAdvance: true,
        scrollIntoView: true,
        allow: [a("demo-library-stage")],
        title: "Choose which details to show",
        body: "Switch Status on cards and Notes on cards off and on to watch the badges on the sample covers disappear and return. Shelves hides or shows the whole shelf row above the library. Hiding a badge only changes what you see; your statuses, notes, and shelves are kept.",
      },
      {
        id: "finish",
        view: "games",
        anchor: a("demo-library-cards"),
        title: "Ready for your own library",
        body: "In My Games, use Select to change a batch of games at once, or right-click a single card and choose Shelves & status. Choices you make in the real Customize panel are remembered the next time you open PlayCounter. Everything from this practice disappears when you finish.",
      },
    ],
  },
  {
    id: "launch-games",
    version: 3,
    kind: "guide",
    category: "detection",
    title: "Launch games directly",
    description:
      "Try a sample launch and learn the optional controller controls.",
    duration: "2 min",
    demoGame: true,
    steps: [
      {
        id: "intro",
        view: "settings",
        anchor: a("settings-launcher"),
        scrollIntoView: true,
        title: "PlayCounter can start games too",
        body: "Direct launching is optional. When enabled, My Games shows Play for games with a usable local launch file or a supported launcher shortcut. Recognition by name alone does not mean a game is installed.",
      },
      {
        id: "enable",
        view: "settings",
        anchor: a("settings-launch-direct"),
        interactive: true,
        manualAdvance: true,
        persistentInteraction: true,
        scrollIntoView: true,
        allow: [a("settings-launch-direct")],
        title: "Choose whether to enable it",
        body: "This checkbox controls direct launching and saves immediately. It requires Remember launch paths. If disabled, you can enable that prerequisite after the guide. You can leave your settings as they are and continue.",
      },
      {
        id: "learned",
        view: "games",
        anchor: a("demo-game-card"),
        anchorTargets: [
          a("demo-game-details"),
          a("demo-game-name-dialog"),
          a("demo-report-dialog"),
          a("demo-remove-dialog"),
          a("demo-game-action-dialog"),
          a("demo-sample-search"),
          a("demo-adjust-dialog"),
          a("demo-log-session-dialog"),
          a("demo-action-result"),
          a("demo-launch-play"),
        ],
        interactive: true,
        manualAdvance: true,
        allow: [
          a("demo-game-card"),
          a("demo-context-menu"),
          a("demo-playtime-menu"),
          a("demo-launch-menu"),
          a("demo-matching-menu"),
          a("demo-library-menu"),
          a("demo-library-modal"),
          a("demo-log-session-backdrop"),
          a("demo-action-result"),
        ],
        title: "PlayCounter learns launch files locally",
        body: "Start a game the usual way. If PlayCounter can learn a usable launch path, its card gets a Play button. Try Play on this sample; no program is started.",
      },
      {
        id: "set-forget",
        view: "games",
        anchor: a("demo-game-card"),
        anchorTargets: [
          a("demo-game-details"),
          a("demo-game-name-dialog"),
          a("demo-report-dialog"),
          a("demo-remove-dialog"),
          a("demo-game-action-dialog"),
          a("demo-sample-search"),
          a("demo-adjust-dialog"),
          a("demo-log-session-dialog"),
          a("demo-action-result"),
          a("demo-menu-launch-options"),
        ],
        interactive: true,
        manualAdvance: true,
        allow: [
          a("demo-game-card"),
          a("demo-context-menu"),
          a("demo-playtime-menu"),
          a("demo-launch-menu"),
          a("demo-matching-menu"),
          a("demo-library-menu"),
          a("demo-library-modal"),
          a("demo-log-session-backdrop"),
          a("demo-action-result"),
        ],
        backTo: "learned",
        title: "Change or forget a launch file",
        body: "Open Launch options and try Set or change launch file. The sample lets you choose or forget a bundled example path. For real games, select the game executable. A missing or forgotten launch path removes direct Play until a usable path is available again.",
      },
      {
        id: "limits",
        view: "settings",
        anchor: a("settings-launcher"),
        scrollIntoView: true,
        title: "Some games still need their usual launcher",
        body: "PlayCounter starts the .exe directly, so games that need Steam, Epic, or extra startup steps may only work from their normal launcher.",
      },
      {
        id: "privacy",
        view: "settings",
        anchor: a("settings-launcher"),
        scrollIntoView: true,
        title: "Paths stay on this PC",
        body: "Saved launch paths never leave your device and aren't included in backups. Turn Remember launch paths off to clear them and stop learning new ones without touching your games or history.",
      },
      {
        id: "controller",
        view: "settings",
        anchor: a("settings-controller-navigation"),
        interactive: true,
        manualAdvance: true,
        persistentInteraction: true,
        allow: [a("settings-controller-navigation")],
        scrollIntoView: true,
        title: "Optional controller navigation",
        body: "This checkbox enables controller navigation and saves immediately. It requires direct launching. With a controller connected, you can move around PlayCounter. To bring PlayCounter to the front, hold Select/View + R1/RB a few seconds and then release.",
      },
    ],
  },
  {
    id: "log-playtime",
    version: 3,
    kind: "guide",
    category: "playtime",
    title: "Log missed playtime",
    description: "Practice adding a session from a game's right-click menu.",
    duration: "2 min",
    demoGame: true,
    finishView: "games",
    steps: [
      {
        id: "intro",
        view: "games",
        title: "Log playtime by hand",
        body: "We'll use a sample World of Warcraft card. Nothing you do here is saved, and your real games can't be changed while the guide runs.",
      },
      {
        id: "open-menu",
        view: "games",
        interactive: true,
        anchor: a("demo-game-card"),
        allow: [a("demo-game-card")],
        advanceOn: {
          type: "anchor-present",
          selector: a("demo-menu-playtime"),
        },
        skipTo: "alternative",
        title: "Right-click the sample card",
        body: "Every game card has a right-click menu with advanced actions.",
      },
      {
        id: "open-playtime",
        view: "games",
        interactive: true,
        anchor: a("demo-menu-playtime"),
        allow: [a("demo-context-menu")],
        advanceOn: {
          type: "anchor-present",
          selector: a("demo-menu-log-session"),
        },
        retreatWhenMissing: a("demo-context-menu"),
        backTo: "open-menu",
        skipTo: "alternative",
        title: "Open Playtime",
        body: "Open this submenu to add a missed session or correct a total. You can also focus it and press the Right arrow key.",
      },
      {
        id: "pick-item",
        view: "games",
        interactive: true,
        anchor: a("demo-menu-log-session"),
        allow: [a("demo-context-menu"), a("demo-playtime-menu")],
        advanceOn: {
          type: "anchor-present",
          selector: a("demo-log-session-dialog"),
        },
        retreatWhenMissing: a("demo-playtime-menu"),
        backTo: "open-playtime",
        skipTo: "alternative",
        title: "Choose “Log missed session”",
        body: "For a real game, this adds a session to History and updates charts and achievements.",
      },
      {
        id: "fill-dialog",
        view: "games",
        interactive: true,
        anchor: a("demo-log-session-dialog"),
        allow: [a("demo-log-session-backdrop")],
        advanceOn: { type: "event", name: "mygames.demo-session-logged" },
        retreatWhenMissing: a("demo-log-session-dialog"),
        backTo: "open-menu",
        skipTo: "alternative",
        title: "Enter length and end time",
        body: "Choose how long you played and when the session ended, then press Log session.",
      },
      {
        id: "result",
        view: "games",
        anchor: a("demo-playtime-result"),
        backTo: "open-menu",
        title: "Playtime and session updated",
        body: "The duration you entered was added to the game's total playtime, and one new session was created. For a real game, that session also appears in History and contributes to charts and achievements.",
      },
      {
        id: "alternative",
        view: "games",
        anchor: a("demo-game-card"),
        anchorTargets: [
          a("demo-game-details"),
          a("demo-game-name-dialog"),
          a("demo-report-dialog"),
          a("demo-remove-dialog"),
          a("demo-game-action-dialog"),
          a("demo-sample-search"),
          a("demo-adjust-dialog"),
          a("demo-log-session-dialog"),
          a("demo-action-result"),
          a("demo-menu-playtime"),
        ],
        interactive: true,
        manualAdvance: true,
        allow: [
          a("demo-game-card"),
          a("demo-context-menu"),
          a("demo-playtime-menu"),
          a("demo-launch-menu"),
          a("demo-matching-menu"),
          a("demo-library-menu"),
          a("demo-library-modal"),
          a("demo-log-session-backdrop"),
          a("demo-action-result"),
        ],
        backTo: "open-menu",
        title: "Only know a total?",
        body: "Open Playtime and choose Adjust total playtime when you only know a lifetime total. It corrects the number without inventing history entries. You're now ready to try either option on one of your own games.",
      },
    ],
  },
  {
    id: "game-actions",
    version: 4,
    kind: "guide",
    category: "library",
    title: "Manage a game in your library",
    description: "Practice history, playtime, matching, and removal actions.",
    duration: "2 min",
    demoGame: true,
    finishView: "games",
    steps: [
      {
        id: "intro",
        view: "games",
        anchor: a("demo-game-card"),
        title: "More actions for every game",
        body: "Every card in My Games has a right-click menu. It's where you fix playtime, correct a wrong match, or get rid of a game.\n\nWe'll use a sample card, so nothing in your library can change.",
      },
      {
        id: "open-menu",
        view: "games",
        interactive: true,
        anchor: a("demo-game-card"),
        allow: [a("demo-game-card")],
        advanceOn: {
          type: "anchor-present",
          selector: a("demo-menu-show-history"),
        },
        skipTo: "history",
        title: "Right-click the sample card",
        body: "Which items you get depends on where the game came from. This sample is a community match, so you see what a matched game offers. A game you added yourself has a few different items.",
      },
      {
        id: "details",
        view: "games",
        anchor: a("demo-game-card"),
        anchorTargets: [a("demo-game-details"), a("demo-menu-details")],
        interactive: true,
        manualAdvance: true,
        backTo: "open-menu",
        allow: [
          a("demo-game-card"),
          a("demo-context-menu"),
          a("demo-library-modal"),
          a("demo-library-menu"),
        ],
        title: "Look inside the game details",
        body: "Choose Open Details and try General and Files. General brings together the game's information and playtime. Files separates known executable matches from saved local launch paths. A known filename alone does not mean the game is installed. This sample uses local data only.",
      },
      {
        id: "history",
        view: "games",
        anchor: a("demo-game-card"),
        anchorTargets: [
          a("demo-game-details"),
          a("demo-game-name-dialog"),
          a("demo-report-dialog"),
          a("demo-remove-dialog"),
          a("demo-game-action-dialog"),
          a("demo-sample-search"),
          a("demo-adjust-dialog"),
          a("demo-log-session-dialog"),
          a("demo-action-result"),
          a("demo-menu-show-history"),
        ],
        interactive: true,
        manualAdvance: true,
        allow: [
          a("demo-game-card"),
          a("demo-context-menu"),
          a("demo-playtime-menu"),
          a("demo-launch-menu"),
          a("demo-matching-menu"),
          a("demo-library-menu"),
          a("demo-library-modal"),
          a("demo-log-session-backdrop"),
          a("demo-action-result"),
        ],
        backTo: "open-menu",
        title: "See only this game's sessions",
        body: "Try Show History to open sample sessions. In your library, it opens My History filtered to the game you chose.",
      },
      {
        id: "playtime",
        view: "games",
        anchor: a("demo-game-card"),
        anchorTargets: [
          a("demo-game-details"),
          a("demo-game-name-dialog"),
          a("demo-report-dialog"),
          a("demo-remove-dialog"),
          a("demo-game-action-dialog"),
          a("demo-sample-search"),
          a("demo-adjust-dialog"),
          a("demo-log-session-dialog"),
          a("demo-action-result"),
          a("demo-menu-playtime"),
        ],
        interactive: true,
        manualAdvance: true,
        allow: [
          a("demo-game-card"),
          a("demo-context-menu"),
          a("demo-playtime-menu"),
          a("demo-launch-menu"),
          a("demo-matching-menu"),
          a("demo-library-menu"),
          a("demo-library-modal"),
          a("demo-log-session-backdrop"),
          a("demo-action-result"),
        ],
        backTo: "open-menu",
        title: "Add playtime that's missing",
        body: "Open Playtime for two options: Log missed session adds one session with the date and length you enter. Adjust total playtime changes only the lifetime number - useful when you carry a total over from a launcher.",
      },
      {
        id: "matches",
        view: "games",
        anchor: a("demo-game-card"),
        anchorTargets: [
          a("demo-game-details"),
          a("demo-game-name-dialog"),
          a("demo-report-dialog"),
          a("demo-remove-dialog"),
          a("demo-game-action-dialog"),
          a("demo-sample-search"),
          a("demo-adjust-dialog"),
          a("demo-log-session-dialog"),
          a("demo-action-result"),
          a("demo-menu-matching"),
        ],
        interactive: true,
        manualAdvance: true,
        allow: [
          a("demo-game-card"),
          a("demo-context-menu"),
          a("demo-playtime-menu"),
          a("demo-launch-menu"),
          a("demo-matching-menu"),
          a("demo-library-menu"),
          a("demo-library-modal"),
          a("demo-log-session-backdrop"),
          a("demo-action-result"),
        ],
        backTo: "open-menu",
        title: "Look the game up again",
        body: "Open Matching and choose Check for Matches. This sample opens bundled results for you to review. In the real library, it checks IGDB and Community matches for the filename again; a custom game can become a matched game.",
      },
      {
        id: "wrong-match",
        view: "games",
        anchor: a("demo-game-card"),
        anchorTargets: [
          a("demo-game-details"),
          a("demo-game-name-dialog"),
          a("demo-report-dialog"),
          a("demo-remove-dialog"),
          a("demo-game-action-dialog"),
          a("demo-sample-search"),
          a("demo-adjust-dialog"),
          a("demo-log-session-dialog"),
          a("demo-action-result"),
          a("demo-menu-matching"),
        ],
        interactive: true,
        manualAdvance: true,
        allow: [
          a("demo-game-card"),
          a("demo-context-menu"),
          a("demo-playtime-menu"),
          a("demo-launch-menu"),
          a("demo-matching-menu"),
          a("demo-library-menu"),
          a("demo-library-modal"),
          a("demo-log-session-backdrop"),
          a("demo-action-result"),
        ],
        backTo: "open-menu",
        title: "Fix a wrong match",
        body: "Report Wrong Match starts a review of the correct game. Try the sample review; nothing is submitted. You can also try Convert to Custom Game and enter a name. The sample keeps its playtime and shows your custom name.",
      },
      {
        id: "remove",
        view: "games",
        anchor: a("demo-game-card"),
        anchorTargets: [
          a("demo-game-details"),
          a("demo-game-name-dialog"),
          a("demo-report-dialog"),
          a("demo-remove-dialog"),
          a("demo-game-action-dialog"),
          a("demo-sample-search"),
          a("demo-adjust-dialog"),
          a("demo-log-session-dialog"),
          a("demo-action-result"),
          a("demo-menu-remove"),
        ],
        interactive: true,
        manualAdvance: true,
        allow: [
          a("demo-game-card"),
          a("demo-context-menu"),
          a("demo-playtime-menu"),
          a("demo-launch-menu"),
          a("demo-matching-menu"),
          a("demo-library-menu"),
          a("demo-library-modal"),
          a("demo-log-session-backdrop"),
          a("demo-action-result"),
        ],
        backTo: "open-menu",
        title: "Remove is not the same as ignore",
        body: "Remove from Library takes the game out of My Games and asks whether to keep its sessions. Notes, playthroughs, and shelf membership are removed even when you keep sessions. The game can return the next time you play it.\n\nIgnore Game does the same, and blocks the file on top - so PlayCounter never picks it up again.",
      },
    ],
  },
  {
    id: "fix-detection",
    version: 2,
    kind: "guide",
    category: "detection",
    title: "Fix an unrecognized game",
    description: "Search, review a match, and try a local filename choice.",
    duration: "3 min",
    simulation: "detection",
    finishView: "discovered",
    steps: [
      {
        id: "intro",
        view: "discovered",
        anchor: a("demo-discovery"),
        title: "When a game isn't recognized",
        body: "You'll use the real review controls with a sample Wow.exe. Search results are bundled for practice, so this works offline. Nothing here is saved or submitted.",
      },
      {
        id: "filters",
        view: "discovered",
        anchor: a("demo-discovery"),
        title: "Start in Needs review",
        body: "Discovered groups apps into Needs review, Tracked, and Ignored. The wizard reviews one executable at a time. This sample is running but has no game match yet.",
      },
      {
        id: "wizard",
        view: "discovered",
        anchor: a("demo-discovery"),
        title: "Is this a game?",
        body: "Check the executable name and running status. You can search and share a game match, keep a custom name only on this PC, ignore a tool, or skip an app you are unsure about.",
      },
      {
        id: "add-share",
        view: "discovered",
        anchor: a("demo-discovery"),
        anchorTargets: [a("demo-sample-search")],
        interactive: true,
        manualAdvance: true,
        allow: [a("demo-library-stage"), a("demo-library-modal")],
        title: "Search, check, and confirm",
        body: "Click Add & Share. Search for World of Warcraft, choose its cover, then confirm the sample match. In your real library, Add & Share submits a suggestion for review. Here the result stays in this guide.",
      },
      {
        id: "add-custom",
        view: "discovered",
        anchor: a("demo-discovery"),
        interactive: true,
        manualAdvance: true,
        allow: [a("demo-library-stage")],
        title: "Keep a custom game local",
        body: "Try Add as Custom, enter a name, and save it. This is useful for private builds, mods, and prototypes. It creates no shared filename match.",
      },
      {
        id: "ignore",
        view: "discovered",
        anchor: a("demo-discovery"),
        interactive: true,
        manualAdvance: true,
        allow: [a("demo-library-stage")],
        title: "Ignore a tool or launcher",
        body: "Try Ignore. In Discovered, this stops tracking the executable. You can restore it later from Ignored. Your sharing preference separately controls anonymous ignore reports.",
      },
      {
        id: "skip",
        view: "discovered",
        anchor: a("demo-discovery"),
        interactive: true,
        manualAdvance: true,
        allow: [a("demo-library-stage")],
        title: "Leave an uncertain app for later",
        body: "Try Skip for now. The app stays in Needs review; skipping does not create a match or ignore it.",
      },
      {
        id: "ambiguous",
        view: "now",
        anchor: a("demo-ambiguous"),
        interactive: true,
        manualAdvance: true,
        allow: [a("demo-library-stage")],
        title: "One filename, several possible games",
        body: "Choose a game from the sample picker. Now Playing asks this when a filename could belong to several games. Your choice is remembered on this PC; it does not become a global match for everyone else.",
      },
    ],
  },
  {
    id: "stats",
    version: 2,
    kind: "guide",
    category: "playtime",
    title: "Read your stats",
    description: "Explore sample sessions, ranges, and charts.",
    duration: "2 min",
    simulation: "stats",
    finishView: "history",
    steps: [
      {
        id: "intro",
        view: "history",
        anchor: a("demo-stats"),
        title: "Your history, with sample sessions",
        body: "This practice history contains six completed sessions spread over several weeks. Next you'll explore ranges, charts, and session actions; your own history stays unchanged.",
      },
      {
        id: "sessions",
        view: "history",
        anchor: a("demo-stats"),
        interactive: true,
        manualAdvance: true,
        allow: [
          a("demo-library-stage"),
          a("demo-library-menu"),
          a("demo-library-modal"),
        ],
        title: "Compare a week with all time",
        body: "Use the range chips to scope the page. Notice how hours and session count change. A highlight takes you to the sessions behind it. Right-click a session to filter by game, open its journal, or practice deleting it.",
      },
      {
        id: "charts",
        view: "history",
        anchor: a("demo-stats"),
        interactive: true,
        manualAdvance: true,
        allow: [
          a("demo-library-stage"),
          a("demo-library-menu"),
          a("demo-library-modal"),
        ],
        title: "Explore Insights and Games",
        body: "Insights is open now. Change the range and inspect the charts. Games ranks your playtime by game. Sessions returns to the timeline. Imported launcher totals do not invent past sessions for these charts.",
      },
      {
        id: "milestones",
        view: "history",
        anchor: a("demo-stats"),
        title: "Milestones and launcher achievements",
        body: "PlayCounter milestones reward local tracking, such as reaching a playtime goal. Provider achievements come from supported launcher imports and belong to individual games. They are separate systems. Find local milestones under Achievements. Imported provider achievements appear in the details of supported games.",
      },
    ],
  },
  {
    id: "import-library",
    version: 1,
    kind: "guide",
    category: "library",
    title: "Import a launcher library",
    description: "Review an optional import and confirm a sample game.",
    duration: "2 min",
    simulation: "import",
    finishView: "games",
    steps: [
      {
        id: "intro",
        view: "games",
        anchor: a("demo-import"),
        title: "Imports are optional",
        body: "PlayCounter detects games automatically, regardless of launcher. Steam, Xbox, and Battle.net imports can help bring an existing library across. This practice does not scan your PC, sign in, or contact a provider.",
      },
      {
        id: "review",
        view: "games",
        anchor: a("demo-import"),
        interactive: true,
        manualAdvance: true,
        allow: [a("demo-library-stage")],
        title: "Review the game and executable",
        body: "Choose a provider. One eligible game executable is preselected here; launcher and updater files are excluded. If several files are eligible in a real import, choose the game executable. Review the suggested title and cover before confirming.",
      },
      {
        id: "confirm",
        view: "games",
        anchor: a("demo-import"),
        interactive: true,
        manualAdvance: true,
        allow: [a("demo-library-stage")],
        title: "Confirm and Import",
        body: "Try searching the bundled sample titles, select the exact game, then click Confirm and Import. Selecting a suggestion alone imports nothing. The result here is temporary.",
      },
      {
        id: "totals",
        view: "games",
        anchor: a("demo-import"),
        title: "Imported time and tracked sessions",
        body: "Steam and Xbox can supply launcher playtime totals. Those totals do not create a made-up session history. Battle.net does not provide past playtime here. Future sessions tracked by PlayCounter build History. A provider badge describes where a game came from; a file-match badge explains recognition.",
      },
    ],
  },
  {
    id: "settings",
    version: 2,
    kind: "guide",
    category: "settings",
    title: "Personalize PlayCounter",
    description: "Walk through key settings and adjust them as you go.",
    duration: "2 min",
    steps: [
      {
        id: "intro",
        view: "settings",
        title: "Settings, your way",
        body: "This guide walks through the most useful preferences. Controls inside each highlighted panel stay active, and any changes you make are real and saved immediately.",
      },
      {
        id: "general",
        view: "settings",
        anchor: a("settings-general"),
        interactive: true,
        manualAdvance: true,
        persistentInteraction: true,
        scrollIntoView: true,
        allow: [a("settings-general")],
        title: "General behavior",
        body: "Turn on Launch on startup if you want tracking ready when you sign in. PlayCounter records sessions while it is running.\n\nBelow that you can switch long playtimes to days and hours.",
      },
      {
        id: "appearance",
        view: "settings",
        anchor: a("settings-appearance"),
        interactive: true,
        manualAdvance: true,
        persistentInteraction: true,
        scrollIntoView: true,
        allow: [a("settings-appearance")],
        title: "Choose your accent",
        body: "Pick the accent color used for buttons, highlights, and focus states. Try a color now, or use Reset to return to the PlayCounter default.",
      },
      {
        id: "notifications",
        view: "settings",
        anchor: a("settings-notifications"),
        optional: true,
        interactive: true,
        manualAdvance: true,
        persistentInteraction: true,
        scrollIntoView: true,
        allow: [a("settings-notifications")],
        title: "Desktop popups",
        body: "Short popups on your desktop while you play. Turn the main switch on first, then pick which events are worth a popup: first-time detections, every game start, session summaries, milestones, or new discoveries.",
      },
      {
        id: "sharing",
        view: "settings",
        anchor: a("settings-sharing"),
        interactive: true,
        manualAdvance: true,
        persistentInteraction: true,
        scrollIntoView: true,
        allow: [a("settings-sharing")],
        title: "Help improve detection",
        body: "When enabled, ignoring an unknown app sends its filename, platform, and anonymous install ID to help improve detection. This setting controls ignore reports; those reports do not include your playtime, history, or notes.",
      },
      {
        id: "updates",
        view: "settings",
        anchor: a("settings-updates"),
        scrollIntoView: true,
        title: "Keep PlayCounter current",
        body: "After the guide, use Check for updates whenever you like. This panel shows which version you are running, whether a new one is available, and the release notes.",
      },
    ],
  },
  {
    id: "backup-data",
    version: 3,
    release: "1.1.17",
    kind: "guide",
    category: "settings",
    title: "Back up or move your data",
    description:
      "Automatic backups, export, and restoring your data on another PC.",
    duration: "2 min",
    steps: [
      {
        id: "intro",
        view: "settings",
        title: "Your data stays portable",
        body: "Open Settings and find Backup & transfer whenever you want to protect your local data or move PlayCounter to another PC. This guide explains both actions without opening a file dialog or changing your data.",
      },
      {
        id: "overview",
        view: "settings",
        anchor: a("settings-backup"),
        scrollIntoView: true,
        title: "Backup & transfer",
        body: "A backup is a single JSON file. It contains your play history, your games, your notes, playthroughs, shelves, and app settings. Saved launch paths are not included; they stay on this PC.",
      },
      {
        id: "automatic",
        view: "settings",
        anchor: a("settings-backup-enabled"),
        scrollIntoView: true,
        title: "Automatic backups",
        body: "By default, PlayCounter saves a backup once a week and keeps the last five. If a backup was missed because PlayCounter was not running, it is saved the next time you open the app. This guide only points at the controls; it does not change your settings or create a backup.",
      },
      {
        id: "schedule",
        view: "settings",
        anchor: a("settings-backup-interval"),
        additionalAnchors: [
          a("settings-backup-keep"),
          a("settings-backup-now"),
        ],
        scrollIntoView: true,
        title: "Choose how often, and how many to keep",
        body: "Schedule switches between daily and weekly backups. Keep sets how many backups stay on disk; once the limit is reached, the oldest automatic backup is deleted. Back up now saves a backup right away.",
      },
      {
        id: "folder",
        view: "settings",
        anchor: a("settings-backup-choose-folder"),
        additionalAnchors: [a("settings-backup-open-folder")],
        scrollIntoView: true,
        title: "Know where your backups are",
        body: "Automatic backups go to PlayCounter's app data folder unless you pick another one with Choose folder. Open folder shows the files. For extra safety, pick a folder that is synced to the cloud or included in your own backups.",
      },
      {
        id: "export",
        view: "settings",
        anchor: a("settings-backup-export"),
        scrollIntoView: true,
        title: "Export your data",
        body: "Choose Export to save the current local data as a JSON file. Keep that file somewhere safe or copy it to the PC where you want to continue using PlayCounter.",
      },
      {
        id: "import",
        view: "settings",
        anchor: a("settings-backup-import"),
        scrollIntoView: true,
        title: "Import a backup",
        body: "Choose Import and select a PlayCounter backup file. Import replaces the current local data; PlayCounter automatically creates a safety backup of the current state first. The button stays locked during this guide to avoid an accidental import.",
      },
    ],
  },
  {
    id: "feedback-replies",
    version: 2,
    kind: "guide",
    category: "settings",
    release: "1.1.17",
    title: "Find replies to your feedback",
    description: "See where replies to your feedback show up.",
    duration: "30 sec",
    steps: [
      {
        id: "send",
        view: "keep",
        anchor: a("send-feedback"),
        title: "Report a bug or suggest a feature",
        body: "Use Help & Feedback to report a bug, ask a question, or suggest a feature. When we answer, the reply shows up right here in PlayCounter. This guide shows a sample reply and does not send anything.",
      },
      {
        id: "bell",
        view: "keep",
        anchor: a("demo-feedback-notification"),
        positionAnchor: a("demo-feedback-panel"),
        additionalAnchors: [a("notifications-bell")],
        title: "Replies appear under the bell",
        body: "Replies show up in Notifications, together with other PlayCounter updates. This one is a sample; your real notifications and unread count are not changed.",
      },
      {
        id: "context",
        view: "keep",
        anchor: a("demo-feedback-original"),
        positionAnchor: a("demo-feedback-panel"),
        additionalAnchors: [a("demo-feedback-reply")],
        title: "Your message stays with the answer",
        body: "Your own message is quoted above the reply, so you always know what the answer is about. Replies are delivered to the PlayCounter installation that sent the feedback, so check the bell on this PC after you send something.",
      },
    ],
  },
  {
    id: "emulators",
    version: 4,
    release: "1.1.17",
    kind: "guide",
    category: "detection",
    title: "Track emulator games",
    description:
      "Learn how PlayCounter detects games running inside emulators.",
    duration: "2 min",
    demoGame: true,
    finishView: "games",
    steps: [
      {
        id: "intro",
        view: "settings",
        title: "Games inside emulators",
        body: "PlayCounter can recognize games inside Dolphin, DOSBox, and PCSX2. This guide uses a sample Dolphin setup. You can confirm and change its match; nothing is saved or shared.",
      },
      {
        id: "settings",
        view: "settings",
        anchor: a("settings-emulators"),
        scrollIntoView: true,
        title: "Enable emulator detection",
        body: "This is where you enable emulator detection. PlayCounter uses local launch details to identify the loaded game. Lookups send the recognized title or disc ID, never a full local path or window title. This step only shows the setting.",
      },
      {
        id: "menu",
        view: "keep",
        anchor: a("nav-emulators"),
        title: "Live view and saved emulator pages",
        body: "An emulator page is added the first time PlayCounter sees that emulator running, and stays afterward. Now Emulating works differently: it appears while an emulator is running. The section is hidden if detection is off or all known emulators are ignored. This guide supplies Dolphin as an example.",
      },
      {
        id: "now-emulating",
        view: "emulating",
        anchor: a("demo-emulator-now"),
        additionalAnchors: [a("nav-emulating")],
        cardPlacement: "below",
        title: "See the loaded game",
        body: "Now Emulating shows the loaded game, its running timer, and the emulator. If the game cannot be identified, a picker asks you to choose it. This session is a sample.",
      },
      {
        id: "emulator-page",
        view: "dolphin",
        anchor: a("nav-dolphin"),
        title: "The Dolphin page stays",
        body: "This page holds Dolphin playtime, sessions, and all of its game matches. You can open it even when Dolphin is not running.",
      },
      {
        id: "linked-games",
        view: "dolphin",
        anchor: a("demo-emulator-linked"),
        cardPlacement: "below",
        title: "Your linked games",
        body: "Each card connects a game to a local file or disc ID. Once linked, PlayCounter recognizes that content again without asking every time.",
      },
      {
        id: "confirm",
        view: "dolphin",
        anchor: a("demo-emulator-linked"),
        anchorTargets: [
          a("demo-emulator-confirmation"),
          a("demo-sample-search"),
          a("demo-emulator-result"),
          a("demo-emulator-confirm"),
        ],
        interactive: true,
        manualAdvance: true,
        allow: [
          a("demo-emulator-linked"),
          a("demo-emulator-result"),
          a("demo-library-modal"),
        ],
        additionalAnchors: [a("demo-emulator-check-badge")],
        title: "Check this once",
        body: "Check that the title is the game you just started. Click Looks right on the sample. The check badge disappears and its sessions stay intact.",
      },
      {
        id: "fix-match",
        view: "dolphin",
        anchor: a("demo-emulator-linked"),
        anchorTargets: [
          a("demo-emulator-confirmation"),
          a("demo-sample-search"),
          a("demo-emulator-result"),
        ],
        interactive: true,
        manualAdvance: true,
        allow: [
          a("demo-emulator-linked"),
          a("demo-emulator-result"),
          a("demo-library-modal"),
        ],
        title: "Correct, forget, or preview sharing",
        body: "Try Change to review a different game. Forget removes the match and keeps recorded History. Share match previews what would go to Community review; it sends nothing here. Cancel leaves the sample as it is.",
      },
      {
        id: "pcsx2",
        view: "settings",
        anchor: a("settings-emulators"),
        scrollIntoView: true,
        title: "PlayStation 2 with PCSX2",
        body: "With emulator detection enabled on Windows, start a game in PCSX2. PlayCounter records the loaded PS2 game. Its page appears after the emulator is first seen. A learned game file can also support direct launching.",
      },
      {
        id: "library",
        view: "games",
        anchor: a("demo-game-card"),
        title: "One shared library",
        body: "Completed emulator sessions appear in My Games and History with native PC games. This sample card carries a Dolphin badge. Provider origins, emulator badges, and file-match sources describe different things.",
      },
    ],
  },
  {
    id: "source-badges",
    version: 2,
    kind: "guide",
    category: "detection",
    title: "Understand game badges",
    description: "Learn how PlayCounter recognized each of your games.",
    duration: "1 min",
    demoGame: true,
    finishView: "games",
    steps: [
      {
        id: "intro",
        view: "games",
        title: "How was this game recognized?",
        body: "A badge tells you how PlayCounter connected the file you started to a game. There are three ways, and we'll show all of them on this sample card - nothing is added to your library.",
      },
      {
        id: "origins",
        view: "games",
        anchor: a("demo-origin-examples"),
        title: "Where it came from, and how it was recognized",
        body: "Steam, Xbox, and Battle.net badges describe a library's launcher origin. Dolphin and other emulator badges describe how the game ran. Community, IGDB, and Custom describe the file match. A game can have both kinds of badge. These examples do not claim that any launcher or game is installed.",
      },
      {
        id: "community",
        view: "games",
        anchor: a("demo-source-community"),
        title: "Community",
        body: "The PlayCounter community database links file names to the right games. You can share a match that's missing - once it's reviewed and approved, everyone's PlayCounter recognizes that file automatically.",
      },
      {
        id: "igdb",
        view: "games",
        anchor: a("demo-source-igdb"),
        title: "IGDB",
        body: "IGDB is a large public game database. Some of its entries record the name of the game's .exe file - bg3.exe for Baldur's Gate 3, for example. When it's there, PlayCounter finds the game right away.\n\nPlenty of entries don't have it, though. That's the gap the Community database fills.",
      },
      {
        id: "custom",
        view: "games",
        anchor: a("demo-source-custom"),
        title: "Custom",
        body: "You added this game yourself. The name and the file it points to stay on this PC, unless you send it to the Community database later.",
      },
    ],
  },
];

export const CORE_TOUR_ID = "core";
export const findTour = (id: string) => TOURS.find((tour) => tour.id === id);
export const guideTours = () => TOURS.filter((tour) => tour.kind === "guide");
